hashicorp/consul-template

cli.go
dependency/catalog_nodes.go
dependency/catalog_services.go
dependency/dependency.go
dependency/file.go
dependency/health_service.go
dependency/health_service_test.go
dependency/store_key.go
dependency/store_key_prefix.go
test/helpers.go
watch/view.go
watch/view_test.go
watch/watcher.go
watch/watcher_test.go

Depends on hashicorp/consul#581.

Switch to using hashicorp/consul/api

---

template_test.go

Fixes https://github.com/hashicorp/consul-template/issues/152

Add more tests for parsing JSON

---

dependency/dependency.go
dependency/dependency_test.go

Fixes https://github.com/hashicorp/consul-template/issues/155

Use the proper length when deep copying tags

---

README.md
brain.go
dependency/datacenters.go
dependency/datacenters_test.go
template.go
template_functions.go
template_functions_test.go
template_test.go

Closes #146 
There were a ton of refactors internally that made 146 impossible to merge.

Add datacenters functionality

---

runner.go
runner_test.go
template.go

Quiesce on a per-template basis

---

template_functions.go

Return an error when failing to parse a key dependency

---

dependency/store_key.go
dependency/store_key_test.go

Fixes https://github.com/hashicorp/consul-template/issues/170

Expand the possibilities for keys

---

runner.go
runner_test.go
watch/view.go

Fixes https://github.com/hashicorp/consul-template/issues/168

Buffer data returned from the Watcher

---

.travis.yml
brain.go
brain_test.go
runner_test.go
template_functions.go

Closes https://github.com/hashicorp/consul-template/pull/180
This adds a new Brain API that locks around getting data.
/cc @mitchellh @nelhage

Add brain.recall

---

cli.go
config.go
config_test.go
runner.go
runner_test.go
watch/watcher.go
watch/watcher_test.go

Drain all data without an arbitrary sleep

---

config.go
runner.go
watch/view.go

Default to a 5s retry interval if none is specified

---

dependency/catalog_nodes.go
dependency/store_key_prefix.go

Return the proper error when errors occur

---

runner.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/188
/cc @ryanuber @armon

Record templates that would have rendered separate from those that did

---

runner.go
watch/view.go
watch/view_test.go

Send errors from the view to the watcher's error channel

---

main.go

Allows source to be easily built by centurylink/golang-builder (Docker
image) without a Go environment otherwise installed.

Added canonical import path to main.

---

runner.go
watch/watcher.go
watch/watcher_test.go

Relates to https://github.com/hashicorp/consul-template/issues/205

Warn the user if they have over 128 watches running

---

runner.go
runner_test.go

allow empty config directories

---

cli.go
cli_test.go

Fixes https://github.com/hashicorp/consul-template/issues/227

Return an error if extra args are given

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Add timestamp template function

---

runner.go
runner_test.go

- Fixes https://github.com/hashicorp/consul-template/issues/228
- Fixes https://github.com/hashicorp/consul-template/issues/220
- Fixes https://github.com/hashicorp/consul-template/issues/219

Properly merge with default config + minor bug fixes

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Fixes https://github.com/hashicorp/consul-template/issues/221

Add loop template function

---

config.go
runner.go
runner_test.go
watch/wait.go

Fixes https://github.com/hashicorp/consul-template/issues/239

Ensure CLI config takes precedence

---

README.md
template_functions.go
template_functions_test.go

- Fixes #202 
- Fixes #211 
/cc @ryanuber @etuttle

Improve byKey function to return a map

---

brain.go
runner.go
runner_test.go
template.go
template_test.go
watch/view.go
watch/view_test.go

This does not fix the evil bug, but I uncovered these issues while searching for said bug.
/cc @ryanuber @armon

Handle a few edge cases with concurrency issues

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Allows checking string values against a regular expression.

Added function regexMatch to test values against a regular expression

---

CHANGELOG.md
README.md
template_functions.go
template_functions_test.go
template_test.go

Fixes https://github.com/hashicorp/consul-template/issues/249

Extend the byTag functionality to include anything with tags

---

runner.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/253

Output to stderr too

---

cli.go
cli_test.go
config.go
config_test.go
flags.go
runner_test.go

- Closes https://github.com/hashicorp/consul-template/pull/278
- Fixes https://github.com/hashicorp/consul-template/issues/271
- Fixes https://github.com/hashicorp/consul-template/issues/275
/cc @ryanuber

Better config merging and option parsing

---

CHANGELOG.md
README.md
cli.go
cli_test.go
config.go
config_test.go
runner.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/281

Add support for writing to a pid file

---

.travis.yml
Makefile
runner.go
runner_test.go

Fixes #283 
/cc @ryanuber @marc-

Add a sane timeout for command execution

---

config.go
runner.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/307

Read standard environment variables for config

---

.travis.yml
Makefile
README.md
cli_test.go
dependency/catalog_node.go
dependency/catalog_node_test.go
dependency/catalog_nodes.go
dependency/catalog_nodes_test.go
dependency/catalog_services.go
dependency/dependency_test.go
runner.go
runner_test.go
template.go
template_functions.go
template_functions_test.go
template_test.go

Closes https://github.com/hashicorp/consul-template/pull/306 and fixes a few things
/cc @ryanuber

Add node function

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Fixes https://github.com/hashicorp/consul-template/issues/258
/cc @ryanuber

Add serializers for outputting JSON and YAML from KV

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Fixes https://github.com/hashicorp/consul-template/issues/297
/cc @ryanuber

Add strconv functions

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

This adds a basic plugin system based around string message-passing.

Add plugin system

---

cli.go

Reload configuration on SIGHUP

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

This adds 5 new functions:
- `in` - determines if a needle is in a haystack
- `add`
- `subtract`
- `multiply`
- `divide`
Closes https://github.com/hashicorp/consul-template/pull/360

Add more functions

---

template_functions.go

Closes https://github.com/hashicorp/consul-template/pull/381

Fix typo in reflection that causes add to be wrong

---

cli.go

Please apply this to master, to fix #393

Cleanly handle config reread

---

README.md
config.go

Default max-stale to 1s

---

template_functions.go
template_functions_test.go

Accept an int64 instead of an int in loop

---

README.md
cli_test.go
config.go
config_test.go
runner.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/358
/cc @slackpad @ryanuber

Allow users to specify file permissions

---

dependency/datacenters.go
dependency/file.go
dependency/file_test.go
dependency/vault_secret.go
dependency/vault_token.go
runner_test.go

Fixes https://github.com/hashicorp/consul-template/issues/432

The LastContact for non-Consul things should always be 0

---

template_functions.go
template_functions_test.go

Fixes https://github.com/hashicorp/consul-template/issues/430

Fix broken math functions

---

dependency/vault_token.go

Use the Auth fields when renewing the token

---

dependency/health_service.go
dependency/health_service_test.go

Make node/service status "maintenance" when in maintenance mode

---

README.md
cli.go
cli_test.go
config.go
config_test.go

Not quite ready for merge - need to do a little more testing but wanted to push it up so you can take a look.
Fixes #428

Adds child process reaping so CT can run as PID 1 in a Docker container.

---

template_functions.go
template_functions_test.go

Add support for uint in math functions

---

dependency/health_service.go
dependency/health_service_test.go

First shot on implementing https://github.com/hashicorp/consul-template/issues/482

Make Checks available through HealthService

---

dependency/vault_secret.go

Store secret data on the dependency itself so renewals can succeed

---

cli.go
dependency/dependency_test.go
runner.go
runner_test.go

Testing this now - should fix the rest of https://github.com/hashicorp/consul-template/issues/507.

Adds reap lockout so we don't disturb sub process waiting.

---

runner.go

Switches to the new pooled transport.

---

dependency/catalog_node.go

Fixes https://github.com/hashicorp/consul-template/issues/572
/cc @slackpad @skippy

Do not share catalog node data

---

README.md
config.go
config_test.go
dedup_test.go
runner.go
template.go
template_test.go

Allow specifying per-template delims

---

runner.go
runner_test.go

This should fix #608 by preventing any leaks around quiescence timers and/or buildup of goroutines. We now use a single timer that we push out during the `min` window and then use to fire the final `max` time.

Simplifies quiescence manager to use single timer to prevent races.

---

CHANGELOG.md
README.md
cli_test.go
config.go
config_test.go
runner.go
runner_test.go
watch/wait.go
watch/wait_test.go

Does a rebase on the work from @tgwizard on #589 and adds some tests. While I was in here I also de-nested the wait logic a tiny bit.
/cc @sethvargo

Add template-specific wait timers

---

README.md

Updates pointer to releases.

---

README.md
dependency/vault_secret.go
dependency/vault_secret_test.go

Add support for writing with data

---

template_functions.go

Allow variadic template function for secret

---

logging/logging.go

Log in UTC and log milliseconds

---

Makefile
cli.go
cli_test.go
errors.go
runner.go
scripts/build.sh

This also provides a framework for individual errors to specify their own return code, but this only implements that framework for the child processes.

Exit with the exit status of the child

---

README.md
cli.go
cli_test.go
config.go
config_test.go
mapstructure.go
mapstructure_test.go
signals/mapstructure.go
signals/mapstructure_test.go
signals/nil.go
signals/signals.go

Add configurable signals for forwarding

---

dependency/catalog_node.go
dependency/catalog_node_test.go

Add service address to catalog response

---

runner.go

Wait for child process to exit in once mode

---

dedup.go

Wait for all existing dedupe acquire attempts to finish

---

README.md

This was harder than I expected, so I thought it might be worth an example.
Based on the info found in:
https://github.com/hashicorp/consul-template/issues/344

[README.md] add memcached example

---

manager/runner.go
manager/runner_test.go

This PR adds two channels, one for when a template has been rendered and one for when all templates have been rendered.

Add ability to watch for a template being rendered and all templates rendered

---

Makefile
dependency/store_key.go
template/template.go
template/template_functions.go
template/template_functions_test.go
template/template_test.go

Add key_exists function

---

cli.go
cli_test.go

Fixes https://github.com/hashicorp/consul-template/issues/741

Fix -renew-token flag

---

cli.go
cli_test.go

Fixes https://github.com/hashicorp/consul-template/issues/740

Add -vault-addr CLI flag

---

manager/runner_test.go

fix template ordering test output

---

README.md
template/scratch.go
template/scratch_test.go
template/template.go
template/template_test.go

Add support for a scratchpad

---

template/funcs.go
template/template.go
template/template_test.go

Add executeTemplate function

---

dependency/store_key_prefix.go
dependency/store_key_test.go

Allow stars in key names

---

config/dedup.go
config/dedup_test.go

Ensure default values for dedup

---

manager/renderer.go
manager/runner.go
manager/runner_test.go

Fix exec panic

---

manager/runner.go

This would only occur in parallel test land, but still work fixing

Fix data race

---

manager/runner.go
template/template.go
template/template_test.go

Show the location where the template died

---

CHANGELOG.md
README.md
template/funcs.go
template/template.go
template/template_test.go

Add base64 template functions

---

template/funcs.go

Properly parse different vault dep types
Fixes GH-844

	Properly parse different vault dep types

---

dependency/vault_common.go
dependency/vault_list.go
dependency/vault_read.go
dependency/vault_token.go
dependency/vault_write.go

Vault list queries do not have a lease duration

---

manager/runner.go

This PR brings back render times to the render event. While rebasing
Nomad's integration with the runner I realized there is not enough
information to decide whether to restart a task or even if all templates
have been rendered.
The root of the issue is timing. By the time a caller unblocks on the
render channel and retrieves the map of render events, the event
containing the boolean that it would have rendered or did render could
be replaced by a newer render event. This means that both booleans will
be false, and integrators will not know if the event ever rendered or
rendered again.
By just storing the timestamp, it is always possible to tell if the
template never would have rendered (ts = 0) and if there has been an
update since you have last seen it.

Add render times to the RenderEvent

---

dependency/catalog_node.go

Do not alter dependency after it's created

---

CHANGELOG.md
template/funcs.go
template/template_test.go

Use the filter to join on filters

---

config/config.go
config/config_test.go

Copy dedup

---

manager/dedup.go

Close sessions prior to waiting for templates to finish

---

config/config.go
config/vault.go
config/vault_test.go

Read ~/.vault-token if it exists

---

.travis.yml
Makefile
cli_test.go
config/vault.go
config/vault_test.go
dependency/catalog_datacenters_test.go
dependency/catalog_node_test.go
dependency/catalog_nodes_test.go
dependency/catalog_service_test.go
dependency/catalog_services_test.go
dependency/dependency_test.go
dependency/health_service_test.go
dependency/kv_get_test.go
dependency/kv_keys_test.go
dependency/kv_list_test.go
main_test.go
manager/dedup_test.go
manager/manager_test.go
manager/runner_test.go
vendor/github.com/hashicorp/consul/testutil/README.md
vendor/github.com/hashicorp/consul/testutil/server.go
vendor/github.com/hashicorp/consul/testutil/server_methods.go
vendor/github.com/hashicorp/consul/testutil/server_wrapper.go
vendor/github.com/hashicorp/consul/testutil/wait.go
vendor/vendor.json

Read all envvars in Vault SSL

---

dependency/catalog_node.go
dependency/catalog_node_test.go
dependency/catalog_nodes.go
dependency/catalog_nodes_test.go
dependency/catalog_service.go
dependency/catalog_service_test.go

Add support for datacenters

---

watch/dependencies_test.go
watch/view.go
watch/view_test.go

Reset retries on successful contact

---

template/scratch.go
template/scratch_test.go

Return a nil map by default

---

manager/dedup.go

Do not return if data is unchanged

---

docker/Dockerfile

This is a simple solution to issue discussed in #960

Add ca-certificates to docker image

---

CHANGELOG.md
README.md
dependency/catalog_datacenters.go
dependency/catalog_datacenters_test.go
template/funcs.go
template/template_test.go

Add a way to ignore a datacenter with failing health checks

---

README.md
config/config_test.go
config/template.go
config/template_test.go
manager/runner.go
template/template.go
template/template_test.go

Add a configuration for erroring on missing keys

---

docker/alpine/docker-entrypoint.sh

Just a small typo fix in docker entrypoint

---

CHANGELOG.md
README.md
template/funcs.go
template/template.go
template/template_test.go

This should address #1024 and #327.

Add indent function to template

---

README.md

Before there is a better solution to this https://github.com/hashicorp/vault/issues/3414, I think it should at least be documented.

Add note about vault.grace period behaviour

---

template/funcs.go
template/template_test.go

Fixes #1127 by checking if the int value is less than zero.

Return error if indent value is negative integer

---

.travis.yml

- Test against latest version of Consul
- Use more modern go version

Upgrade CI for go and Consul version

---

README.md
config/vault.go
config/vault_test.go
dependency/client_set.go
manager/runner.go

Add support for Vault namespaces

---

README.md
cli.go
cli_test.go
config/vault.go
config/vault_test.go
dependency/vault_agent_token.go
dependency/vault_agent_token_test.go
manager/runner.go
watch/watcher.go

If this parameter is specified:
- CT will not renew token
- will monitor file for changes and reload it

Add vault-agent-token-file configuration parameter for Vault Agent token

---

README.md

document limits on using dots in service names

---

dependency/dependency_test.go
dependency/vault_agent_token_test.go
main_test.go
manager/dedup.go
manager/dedup_test.go
manager/manager_test.go

Fixes to stop test suite from randomly hanging and panicking.

Test suite bandaid

---

config/vault.go

forward compatibility with vault env name change

---

docker/alpine/Dockerfile
docker/light/Dockerfile
docker/scratch/Dockerfile

Updated all Dockerfiles to use build stage instead of copying in local
build. Also made a few small tweaks to alpine build to be more up to
date and consistent with how envconsul is built.

update Dockerfiles to use multi-stage builds

---

manager/runner.go
manager/runner_test.go

Hold off on initializing wait/quiescence until all templates have been
rendered once. This fixes an issue with -exec firing before the template
has been rendered and would also make sure templates are rendered for
once (if that wasn't already fixed another way).
Fixes #1229

init quiescence after all templates are rendered

---

README.md

Updated readme to add space after name

---

manager/runner.go

https://github.com/hashicorp/consul-template/issues/1308

Add DEBUG messages to identify missing dependencies

---

CHANGELOG.md

I'll update the date when doing the actual release.

changelog notes for 0.24.0

---

README.md

README: Add a note on parseFloat and printf

---

docs/configuration.md

PR #1388 already changed whitelist/blacklist to allowlist/denylist, but the
example in the configuration documentation was left out.

Docs: Change whitelist/blacklist to allowlist/denylist

---

dependency/catalog_node_test.go
dependency/catalog_services_test.go
dependency/dependency_test.go
dependency/health_service.go
dependency/health_service_test.go

Adds support for service tagged addresses

---

README.md
docs/templating-language.md

* Fix missing link to Go Template, Consul, etc.
* Add more cross-functions links
* Improve rendering
* Fix debugging functions documentation

Improve template documentation

---

logging/logging.go
logging/logging_test.go
logging/syslog_test.go

Overhauled logging to read better and have testing.
Fixes issue with missing timestamps.
Fixes #1475

rework logging and fix timestamp issue

---

.github/workflows/ci.yml

Adds a basic CI testing workflow using Github Actions.
Getting the basics in place for the new standard.

GitHub Actions based CI

---

README.md

docs on shell + signal handling for exec mode

---

docs/templating-language.md

Thanks Iulian Mandache (@iul1an) for the idea!
Closes #1602

docs on how to use pkiCert w/ CA chain

---

.github/CONTRIBUTING.md
README.md
docs/configuration.md

Was reading the docs and noticed these....

Fix docs: master->main and Nomad link

---

template/funcs.go

generalize a few template funcs input types

---

CHANGELOG.md
version/version.go

updating changelog and version for new release

Update changelog for v0.32.0

---

child/child.go

Adding a comment after discovering a potential race condition in https://github.com/hashicorp/vault/pull/20817.

Add a comment to clarify the usage of child.ExitCh()

---

dependency/catalog_datacenters.go

ref: https://github.com/hashicorp/consul-template/issues/1745

fix: datacenter sort should be by RTT and is instead lexical

---

.github/workflows/build.yml
.github/workflows/ci.yml

recreating: https://github.com/hashicorp/consul-template/pull/1744

SEC-090: Automated trusted workflow pinning

---

go.mod
go.sum

- fixes https://github.com/hashicorp/crt-workflows-common/actions/runs/5757600247/job/15608949123

bump x/net to v0.13.0 fix dependency issue

---

CHANGELOG.md
version/version.go

Add a changelog and version bump for 0.37.4

pre-release updates for 0.37.4

---

go.mod
template/scratch.go

update go version to 1.22.4

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
version/version.go

Updated the release version and changelog files for release details.
PS: some CI tests are failing temporarily for consul-enterprise due to license and vault connection issues and need to be fixed. The release works fine with consul and is prioritized over such issues.

Update CHANGELOG and version files for release 0.40.0 

---

.golangci.yml
template/template.go
template/template_test.go

Add support for denylist on glob patterns like `sprig_*`.

add: denlylist pattern support

---

CHANGELOG.md
version/version.go

This PR updates the release version and CHANGELOG for the `release/0.41.1`.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

stage release/0.41.1

---

.release/security-scan.hcl

This PR suppresses CVEs in alpine containers for which fixes are not yet available.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

suppress open alpine vulnerabilities
