hashicorp/consul-template

README.md
cli.go
config.go
config_test.go

Adds the `https` and `insecure` bool config options for talking to an HTTPS consul instance.
Fixes #143.
/cc @sethvargo

Add options for enabling HTTPS

---

runner.go
watch/watcher.go

As reported in #168, there is a fun data race where Consul Template loops indefinitely when a template reports missing dependencies but the watcher is already watching the dependencies (but has not yet returned data).
This diffs the watcher's list of watches with the dependencies a template is reporting as missing and only restarts the loop if there are unwatched dependencies (not just ones that have not returned data yet).

Diff missing dependencies with unwatched dependencies

---

cli.go

Fixes an issue where SIGHUP would try to reload, but end up stopping consul-template.
@sethvargo can you take a look?

Fix runner scope during SIGHUP handling. Fixes #175.

---

README.md
cli.go
config.go
config_test.go
dependency/datacenters_test.go
runner.go
runner_test.go
test/helpers.go
watch/view.go
watch/view_test.go
watch/watcher.go
watch/watcher_test.go

This adds a new option for `-max-stale` (config and CLI flag) that allows CT to query non-leaders. It also adds a new `-batch-size` option for the user to customize the size of the batch views are processed in.
/cc @mitchellh @armon

Add -max-stale and configurable -batch-size

---

README.md
cli.go
cli_test.go
config.go
config_test.go
flags.go
logging.go
logging_test.go
runner.go
watch/wait.go

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 5a11759..f1f6380 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -3,6 +3,18 @@ Consul Template Changelog
+BREAKING CHANGES:
+
+  * Remove `ssl` configuration option from templates - use an `ssl`
+    configuration block with `enabled = true` instead
+  * Remove `ssl_no_verify` configuration option from templates - use an `ssl`
+    configuration block with `verify = false` instead
+  * Restructure CLI `-ssl-no-verify` to `-ssl-verify` - to disable SSL
+    certification validation on the command line, use `-ssl-verify=false`
+  * Remove `auth` configuration option from templates - use an `auth`
+    configuration block with `enabled = true` combined with `username = ...` and
+    `password = ...` inside the block instead
+ …
```

Add support for logging to syslog

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

This adds a new `byKey` function for the template that accepts a list of KV pairs (most likely from `tree`) and "groups" them by the top-most key. You can see the comment in template_functions.go for a more concrete example of what that might look like.
- Fixes https://github.com/hashicorp/consul-template/issues/207
/cc @ryanuber @armon

Add byKey function for grouping the results of tree by its top key

---

README.md
dependency/health_service.go
dependency/health_service_test.go

This fixes a pretty critical bug in how we filter services, specifically around how we handle "any" vs "passing" vs "(other things)".
"any" is a special case in that it cannot and should not be specified with other status filters. In the past, it was permitted to do this:
```liquid
{{ range services "nginx" "any, passing" }}{{ end }}
```
This led to user confusion. Users thought this meant "give me any service that is passing", but it really means "give me a service that has any status or services that are passing", but since passing services are a subset of any service it was really "give me all services regardless of their status". This was especially confusing for new users and the documentation was a bit unclear. Consul Template now returns an error when you specify additional filters …

Fix service filtering

---

README.md

The using parseJSON is kinda ugly. I.e. the following fails most of the time (but I'm not sure if it always fail):
```
{{ $config := parseJSON (key "config") }}
{{ range $config.items }}
{{ end }}
```
Which is fixed by:
```
{{ $config := parseJSON (key "config") }}
{{ if $config }}
{{ range $config.items }}
{{ end }}
{{ end }}
```
Hopefully my explanation is clear enough.

Describe parseJSON bug

---

README.md
config.go
config_test.go
runner.go
runner_test.go

/cc @armon @ryanuber 
Depends on hashicorp/consul#794

Set envvars in commands

---

README.md

I noticed while walking someone through the examples that they didn't work anymore

Fixed references to "webapp" and "nyc1"

---

template_functions.go
template_functions_test.go

Fixes https://github.com/hashicorp/consul-template/issues/288

Account for empty strings when splitting

---

runner.go
runner_test.go

This should fix #315, but I don't have a Windows environment set up to test at the moment. @highlyunavailable if you want to give this a quick test that would be great, otherwise I'll see if I can get something going on Monday.

Don't error if file doesn't exist initially on Windows

---

dependency/catalog_node.go
dependency/catalog_node_test.go

Change how we sort `NodeService` items in a `NodeServiceList`. This should allow multiple services with the same name to have a consistent ordering based on the unique service `ID`.
Authored using the github web UI and I haven't had a change to build locally. Apologies in advance if this breaks things.

Fix node service list sort when multiple services have the same name.

---

README.md
config.go
config_test.go
dependency/vault_secret.go
dependency/vault_token.go
dependency/vault_token_test.go
runner.go
template_functions.go
watch/watcher.go
watch/watcher_test.go

This is a configuration option that defaults to true. Users can opt-out by setting the configuration option.

Add a way to renew Vault tokens

---

README.md

The Go template "index" function has 2 args. Also, the consul-template `service` function takes an optional second argument as a string.
Examples using these functions in the README have a syntax error and using them as a reference will produce this kind of error:
```
template: haproxy.cfg.ctmpl:35:58: executing "haproxy.cfg.ctmpl" at <0>: expected string; found 0
```

README template index function has 2 args

---

README.md

I had trouble figuring out how plugin names were used until I checked the source code, so I clarified the docs with my (accurate, I hope) interpretation.

Clarify plugin name is actually an executable path

---

runner.go

According to this commit in Go:
https://github.com/golang/go/commit/92c57363e0b4d193c4324e2af6902fe56b7524a0
this has been fixed in Go and is no longer needed.
This fixes GH-378

Do not remove the Windows file if it does not exist.

---

README.md
dependency/store_key.go
dependency/store_key_test.go
template.go
template_functions.go
template_functions_test.go
template_test.go

This new function builds on the existing `key` function, but provides an easy
way for users to specify a default value. This replaces the common pattern of:
{{if key "service/app/max_conns"}}
max_conns={{key "service/app/max_conns"}}
{{else}}
max_conns=500
{{end}}
or
{{ or (key "service/app/max_conns") "5" }}
with
{{ key_or_default "service/app/max_conns" "5" }}
Fixes GH-368

Add key_or_default

---

runner.go

This is mostly for Vault/dev mode to prevent typos.
Fixes GH-361

Push watcher errors down the stack in "once" mode

---

README.md
template_functions.go
template_functions_test.go

Ran into a case where a unix timestamp would be very useful but wouldn't be able to get that out of the timestamp formatting. Thought it might warrant a special case to `timestamp` as opposed to its own function.

add timestamp special case 'unix'

---

.travis.yml
README.md
brain.go
brain_test.go
cli.go
cli_test.go
config.go
config_test.go
dedup.go
dedup_test.go
dependency/catalog_node.go
dependency/catalog_nodes.go
dependency/catalog_services.go
dependency/dependency.go
dependency/dependency_test.go
dependency/health_service.go
dependency/store_key_prefix.go
runner.go
runner_test.go
template.go
template_test.go
watch/watcher.go

This adds a new de-duplication mode which is used to have a single instance of consul-template run the watchers, and the other instances receive the data in a single KV key. This works by:
* Generating a KV prefix based on the hash of the template `prefix = consul-template/dedup/MD5/`
* Locking a key for the template (`prefix/lock`)
* If leader, run views normally, and on render write the dependencies as (`prefix/data`)
* If follower, watch template data (`prefix/data`), re-render on data updates
* Vault data is excluded from this, as it should not be shared
In this system, instead of running 50 queries per template on 50 nodes (2500 queries), we instead run 50 queries on one node, and 100 KV watches on the others, for a total of 150. This results in a dramatic reduction of read pressure …

Adds support for de-duplication of template rendering between multiple instances

---

.gitignore
cli.go
cli_test.go
config.go
config_test.go
runner.go

Setting the config option ssl.key or CLI flag
'-ssl-key=/my/private/key.pem' allows the HTTPS client to authenticate
itself towards a Consul server which has the option "verify_incoming": true
CC: @sorenmat

Introduce TLS/SSL Mutual Authentication

---

README.md
template.go
template_functions.go
template_functions_test.go
template_test.go

Hello, making a pull request adding a trim helper function. Personally find it really handy!
```
go version go1.5.1 darwin/amd64
```
```
go test ./... -run trim
ok  	github.com/hashicorp/consul-template	0.052s
ok  	github.com/hashicorp/consul-template/dependency	0.059s
ok  	github.com/hashicorp/consul-template/logging	0.029s
?   	github.com/hashicorp/consul-template/test	[no test files]
ok  	github.com/hashicorp/consul-template/watch	0.070s
```
Tested locally and it works as intended. But only second time trying my hand at GO so (shrug).

adding a trim helper function

---

README.md

While mentioned in a few places already, the plugin section does not contain a reminder about handling cases before multi-phase execution is resolved (see #542).
Also added a note about providing non-template parameters to plugins.

Clarify plugin requirements wrt multi-phase execution

---

README.md
dependency/vault_secret.go
dependency/vault_secret_test.go
dependency/vault_secrets.go
dependency/vault_secrets_test.go
template.go
template_functions.go
template_functions_test.go
template_test.go

This adds a new template function "secrets" which may be used to list secrets in Vault, provided the endpoint supports it. This commit also renames the "vault" template function to "secret" for consistency with other projects and deprecates the use of the "vault" template function.
Fixes GH-270

Add support for listing secrets

---

cli.go
config.go
dependency/catalog_node.go
dependency/catalog_node_test.go
dependency/catalog_nodes.go
dependency/catalog_nodes_test.go
dependency/catalog_services.go
dependency/catalog_services_test.go
dependency/datacenters.go
dependency/datacenters_test.go
dependency/dependency.go
dependency/file.go
dependency/file_test.go
dependency/health_service.go
dependency/health_service_test.go
dependency/store_key.go
dependency/store_key_prefix.go
dependency/store_key_prefix_test.go
dependency/store_key_test.go
dependency/test.go
dependency/vault_secret.go
dependency/vault_secret_test.go
dependency/vault_secrets.go
dependency/vault_secrets_test.go
dependency/vault_token.go
dependency/vault_token_test.go
template_test.go
watch/view.go
watch/watcher.go
watch/watcher_test.go

Previously, when the watcher stopped a view, there was no way for the underlying dependency to stop fetching. This was especially true if the dependency performed a sleep operation since not all endpoints support blocking queries.
- Fixes GH-534
- Closes GH-537

Allow long-running dependencies to stop on reload

---

template_functions.go
template_functions_test.go

It is perfectly valid to have a key that is both a "key" and a "folder" in Consul's KV store. However, in the "explode" function, it is not possible to represent this, so we return an error.
Fixes GH-596

Print a nice error a node is a root and leaf

---

runner.go
watch/view.go
watch/view_test.go

This is the consul-template side of https://github.com/hashicorp/consul-replicate/issues/29. The old `View` interface was dangerous in that it allowed the outside to fetch its `Data` when the fetching goroutine could be updating it (probably an atomic op to update a pointer, but still sketchy), and most importantly, another fetch could come along and update the `LastIndex` while you are processing an older chunk of data.
This hides all the data-related members and exposes them through accessors that do RW locking, and adds an atomic fetch of data and the last index that goes along with that data.

Protects the view's data and last index from races.

---

config.go
config_test.go
mapstructure.go
mapstructure_test.go

This commit adds a new mapstructure function for automatically decoding into os.FileMode. The function expects the value to be a string in json or a string or int in hcl.
Fixes https://github.com/hashicorp/consul-template/issues/623
/cc @slackpad @cbednarski

Use mapstructure decoder for os.FileMode

---

.travis.yml
README.md
cli.go
cli_test.go
config.go
config_test.go
runner.go
runner_test.go

Just as we did with the official Consul container, we are going to rely on services like dumb-init to handle child process reaping, not the go process itself.
/cc @slackpad

Remove the reaping functionality

---

template_functions.go
template_functions_test.go

The default function for parseJSON currently returns an array. This is problematic.
Fixes GH-635 because it makes using functions like `index` more difficult due to arrays being unable to have string indexes. This should be backwards compatible because one can still index a map using a string (thus treating it as an array).
/cc @slackpad

Return a map instead of an array for parseJSON

---

dependency/store_key_prefix.go
dependency/store_key_prefix_test.go

This relates to https://github.com/hashicorp/consul-replicate/issues/48 (and should fix it). StoreKeyPrefix always needs to be a folder, but Consul Replicate gets confused if it's not. This will ensure the API call looks like a "folder".

Ensure trailing slash and no leading slash

---

dependency/store_key_prefix.go

Spring Cloud Consul has adopted a default prefix that includes a comma
to separate the application name and profile. Prefixes end up looking like
'config/application,profile/'. This commit adds support for these prefixes.
See: http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html
```
config/testApp,dev/
config/testApp/
config/application,dev/
config/application/
```

Allow commas in the prefix.

---

template_functions.go
template_functions_test.go
vendor/github.com/burntsushi/toml/COMPATIBLE
vendor/github.com/burntsushi/toml/COPYING
vendor/github.com/burntsushi/toml/Makefile
vendor/github.com/burntsushi/toml/README.md
vendor/github.com/burntsushi/toml/decode.go
vendor/github.com/burntsushi/toml/decode_meta.go
vendor/github.com/burntsushi/toml/doc.go
vendor/github.com/burntsushi/toml/encode.go
vendor/github.com/burntsushi/toml/encoding_types.go
vendor/github.com/burntsushi/toml/encoding_types_1.1.go
vendor/github.com/burntsushi/toml/lex.go
vendor/github.com/burntsushi/toml/parse.go
vendor/github.com/burntsushi/toml/session.vim
vendor/github.com/burntsushi/toml/type_check.go
vendor/github.com/burntsushi/toml/type_fields.go
vendor/vendor.json

Fits in nicely with `toJSON` and `toYAML`. My own motivation is that I would like to configure [Træfɪk](http://traefik.io/) entirely with Consul-Template, as part of [Mantl](http://mantl.io).
Unfortunately, Burntsushi/toml doesn't support the `Marshal` interface (see https://github.com/BurntSushi/toml/issues/76), so this is slightly more awkward than `toYAML` and `toJSON`. 
Fixes (the already closed) #656.

template functions: toTOML

---

runner.go
runner_test.go

Previously order was not guaranteed because a map was used to ensure
uniqueness. This commit changes the behavior to maintain order, so the
order templates are specified in config are the order they are run.
Fixes GH-683

Maintain template-specified order

---

template_functions.go
template_functions_test.go

Previously, elements would just be detected as type `interface`. Extracting the element directly from the slice and then examining the value allows is true type to be revealed.
Fixes #708

Support checking if an interface slice contains a value.

---

.travis.yml
dependency/store_key_prefix.go
dependency/store_key_prefix_test.go

Do not require a trailing slash for store key prefix

---

README.md
cli.go
cli_test.go
config.go
config_test.go
dependency/client_set.go
dependency/client_set_test.go
dependency/dependency_test.go
runner.go
scripts/dist.sh

This PR adds a method for unwrapping a wrapped token. The user must specify that the provided token is wrapped either via the CLI or configuration file.
Fixes GH-712

Provide a mechanism for unwrapping a token

---

manager/runner.go
manager/runner_test.go
template/template.go

This PR address the fact that the destination is not always needed (in dry mode) and accounts for the fact that wouldRender is triggered even if the content is empty, this makes the old AllRendered implementation broken.
This current implementation gives the caller of the `Runner` all the information they need to track it themselves

Remove AllRendered and push the logic to the user and expose more detail

---

dependency/file.go
dependency/store_key.go
manager/runner_test.go
watch/view.go

This fixes a commonly confusing issue where the `key` function does not actually issue a blocking query. This is because users have, in the past, used the API like this:
{{ if key "foo" }}
feature flag active
{{ else }}
default
{{ end }}
In this model, the existence of a key is the check. With the introduction of `key_or_default`, it makes sense to return `key` to be a blocking query.
/cc @dadgar @slackpad

Issue a blocking query for "key"

---

README.md
template/template.go
template/template_test.go

I noticed this function was added recently, but I wasn't able to actually use it.

expose and document toTOML function added in #675

---

README.md
config/config.go
config/config_test.go
dependency/client_set.go
manager/runner.go

This PR also fixes the Vault environment variables set during exec

Add CAPath config to SSL and use when creating Consul/Vault clients

---

manager/runner.go

Also saw this panic once during testing. It is unrelated but you may want to look at it:
```
panic: Fail in goroutine after TestDatacentersFetch_blocks has completed
goroutine 473 [running]:
panic(0x963060, 0xc4203a8aa0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.(*common).Fail(0xc42025fb00)
/usr/local/go/src/testing/testing.go:412 +0x11f
testing.(*common).FailNow(0xc42025fb00)
/usr/local/go/src/testing/testing.go:431 +0x2b
testing.(*common).Fatal(0xc42025fb00, 0xc42035df60, 0x1, 0x1)
/usr/local/go/src/testing/testing.go:490 +0x6f
github.com/hashicorp/consul-template/dependency.TestDatacentersFetch_blocks.func1(0xc4204d4480, 0xc4204d4330, 0xc42025fb00, 0xc420372300)
/Users/adadgar/Projects/go/src/github.com/hashicorp/consul-template/dependency/datacenters_test.go:41 +0xf5 …
```

Send signal to watching applications on would render

---

Makefile

Not sure what the current code is/was supposed to do, but cut only accepts one ``-f`` argument.
Also the build only works if PROJECT is set to ``github.com/hashicorp/consul-template``

Fix make dev target

---

README.md
template/funcs.go
template/template_test.go

While
{{executeTemplate templateName}}
executes in the context of the parent,
{{executeTemplate templateName data}}
executes in the context given by the argument "data".

executeTemplate: allow optional argument

---

dependency/file.go

The goroutine would never terminate when the file changes and would just
continue looping.

dep: Fix goroutine leak in file watcher

---

README.md

Relates to issue: https://github.com/hashicorp/consul-template/issues/834 where an example in the README.md is missing a `\` to escape the newline.

added missing backslash in example

---

README.md
config/exec.go

This was the default prior to the RC candidate, but appears to have been accidentally overridden during the config refactor.
Fixes GH-835

Default reload signal to null

---

config/retry.go
manager/runner.go

Relates to #799 for early feedback from @dadgar 
This adds a new `TemplateEvents` channel which will push individual template events onto the consumer. The event will include the full list of used dependencies, missing dependencies, and unwatched dependencies, as well as the result of WouldRender and DidRender.
If you like this, I'm fairly certain we can remove the other RenderEvent stuff. Does this give you enough information to do what you need to do?

Add POC for a channel that holds template events

---

README.md

Example syntax for `Scratch.Get` included `Scratch.Key` instead of `Scratch.Get`

 Fix example for Scratch.Get

---

.travis.yml
dependency/catalog_services.go
dependency/file.go
dependency/kv_get.go
dependency/kv_keys.go
dependency/kv_list.go
dependency/vault_list.go
dependency/vault_list_test.go
dependency/vault_read.go
dependency/vault_write.go
template/funcs.go
template/template_test.go

This ensures we always return the zero value for things, even on error.
- Fixes GH-853

Return zero value for functions

---

.travis.yml
cli.go
cli_test.go
config/config.go
config/consul.go
config/vault.go
config/vault_test.go

Previously environment variables would load in the "defaults" section of a configuration, making it impossible to override them during a merge. This PR fixes that and keeps track of the list of configuration paths given on the CLI to fix reloading.
Fixes GH-866

Allow overriding configurations

---

README.md

After a mass replace of '//' to '#' the vault url in the readme was
incorrect. This fixes that.

Fix vault url in readme

---

README.md
cli.go
cli_test.go
config/consul_test.go
config/retry.go
config/retry_test.go
config/vault_test.go

This is a work in progress Pull request so you can have a look already
Questions:
- Should this also be exposed to users via the config file?
- I did not find a test for the RetryFunc itself, did I just overlook it or should I add one?

RetryConfig: Add MaxBackoff option (fixes #938)

---

README.md

There is no unit test for negative number, so let's update the README.
Also setting max_backoff to zero means unlimited max_backoff.

README: Setting attempts to zero means unlimited

---

README.md

`nginx -s reload` might be a better example than an `nginx` restart.

Nginx example update

---

.travis.yml
README.md
config/config_test.go
config/vault.go
config/vault_test.go
dependency/dependency.go
dependency/vault_common.go
dependency/vault_read.go
dependency/vault_token.go
dependency/vault_write.go
manager/runner.go
watch/view.go
watch/watcher.go

This fixes #949 by allowing a configurable Vault grace period. When renewing a secret, if the remaining lease is less than or equal to the configured grace, CT will request a new credential. This prevents Vault from revoking the credential at expiration and CT having to play catchup.

Add Vault grace periods

---

README.md

https://github.com/hashicorp/consul-template/commit/4eb346a15a1450f14cf8824098e1ed731377e401#diff-2a66a49ce9a1ffa85b6805fbf4d82b6a
Fixed #970

dump_signal configuration option was removed in 0.18.0

---

config/vault.go

This PR changes the default Vault grace from 5 seconds to the originally
intended duration of 5 minutes.

Set default Vault Grace to 5 minutes

---

manager/renderer.go

Currently `manager/renderer.go` always sets render output as `existing`, which is the data it read from disk. This means that the render output is actually either:
- empty, if render output file does not exist
- identical data, if file existed and output has not changed
- stale data, if file existed and output changed
This PR fixes the issue by using the latest rendered output as the result.
I made a simple test program to verify this. It is available here: https://gist.github.com/vtorhonen/90f73577e41abddcd0444723a0bfffc1
Steps to reproduce:
- Write test data to Consul KV:
- `consul kv put foo bar`
- `consul kv put foo2 bar2` 
- Download gist and run it `go run render.go`
First run prints out empty data, but it writes the value for key `foo` correctly to file `output`. Next, change …

Return latest rendered data in result output

---

manager/runner.go
manager/runner_test.go

This PR does the following:
* Refactors the Run command to pull the running of individual templates into
their own method.
* Adds a render event channel that is triggered when there is a new render event,
* Fixes a bug in which the event was only added if the template was actually
rendered versus dependencies changing.
@sethvargo for review

Add render event channel and refactor template run

---

manager/runner.go

Previously we could check if an event existed, but now we keep track of more data, meaning we might have an event for an unrendered template. This ensures the event exists AND the template did render.
Fixes GH-991
/cc @dadgar

Check if the template actually rendered

---

README.md
dependency/vault_read.go
dependency/vault_token.go
dependency/vault_write.go

This fixes an issue introduced in
https://github.com/hashicorp/consul-template/commit/e2155b4caa67791e3f98e39cb5842d1033f24cf0
where renewals againsts the generic secret backend that has a TTL close
to the VaultGrace would cause a renewal hotloop.
This fixes https://github.com/hashicorp/nomad/issues/3133

Fix Vault read/renewal hot-loop

---

manager/runner.go
manager/runner_test.go

Currently the template runner writes its output to outStream and errStream. These are hardcoded to `stdout` and `stderr` in the `init()` function. This is particularly problematic when the `manager` package is used in a separate project where stdout/stderr is then polluted by the renderer. I have used a not-so-ideal wrapper as a workaround, which sets `os.Stdout` and `os.Stderr` to `/dev/null` just for a brief moment while calling `manager.NewRunner()`.
This PR adds functions `SetOutStream` and `SetErrStream` making output/error stream customization a lot easier. These functions should be called before starting the runner. If user is not interested in the output/error streams then both streams could be set to for e.g. [`ioutil.Discard`](https://golang.org/pkg/io/ioutil/#pkg-variables).
I …

Add functions for modifying runner out/err streams

---

config/vault.go

users are not surprised by continuous renewals on dynamic secrets with TTLs lower than 5 minutes (the previous default).

Make default grace period match Vault's default, this makes it so 

---

dependency/client_set.go
manager/runner.go

In cases where both `renew_token=true` and `unwrap_token=true` the watcher is trying to renew the wrapping token and not the wrapped token, this change fixes it. It will create a watcher by getting the vault token from Vault client, which will be the unwrapped token in case `unwrap_token=true` is used.

Renew the unwrapped token

---

config/template.go
config/template_test.go

This allows you to write something like:
```shell
consul-template -template "in.ctmpl:out:curl https://google.com:443"
```

Allow colons in the template command on the command line

---

README.md

Fixes #829 
Give an example of how to default an environment variable if it doesn't exist.

Add documentation for a default env variable.

---

examples/vault-pki.md

Tiny fix: [comments](https://golang.org/pkg/text/template/#hdr-Actions) use `/* */`, not `#`.

examples: vault-pki: Fix template comment syntax

---

README.md
dependency/dependency_test.go
main_test.go
manager/manager_test.go

Test fails with a generic failure message if consul is not installed:
```2018/02/15 20:25:12 failed to start consul server```
The `NewTestServer` helper already supports good error messaging for this, but it is swallowed. I have revealed it:
```2018/02/15 21:43:01 consul not found on $PATH - download and install consul or skip this test```
Also updated docs with link to consul install guide.

Document consul dependency for tests

---

README.md

list content must be indented by exactly 4 spaces:
https://markdown-guide.readthedocs.io/en/latest/basics.html#lists-nested
preview:
https://github.com/balupton/consul-template/blob/f98230b26c6eaa6e78dafbbd08e35243922555fc/README.md

readme: fix indentation of quick example

---

manager/runner.go

This PR addresses https://github.com/hashicorp/consul-template/issues/1080

Use DEBUG instead of INFO for the noisy '(runner) initiating run' log

---

child/child.go

If a child process is already dead, calling Stop() or Kill() will wait for the
splay timeout regardless of if the process is already dead or not. This
doesn't appear to cause any problems in consul-template that I could
find, but it _does_ cause an issue in envconsul, which imports this part
of consul-template as a library.
In envconsul, if an -exec-splay is specified, and the child process dies
for some reason (other than that it is being reloaded by envconsul
itself), envconsul will not itself exit until a random splay has
elapsed. This is a really surprising and undesireable behaviour IMO.
This happens because envconsul tries to gracefully shut down by calling
Stop() on the consul-template child object. That in turn calls kill(),
which waits for the splay to elapse. There seems to be …

Fix Child.Kill() waiting for splay if process already dead

---

cli.go
docker/alpine/docker-entrypoint.sh

Instead of relying on the entrypoint to do this, we can just read this in Go, which will make it work in the scratch containers or containers without a shell.
/cc @pearkes

Consume CT_LOCAL_CONFIG in Go

---

manager/runner.go
manager/runner_test.go

Fixes #1043 
Many render events can potentially be created and processed. They're stored in a map by template ID so they typically overwrite other render events. I believe this is all intentional in order to support
the right behaviors for waiting for upstream difference before rendering a template, but it led to an issue where the `exec` child process wouldn't ever be created as these render events were being used
to determine completion of rendering.
I believe this current approach could be improved considerably to be less prone to these types of issues, however this patch tries to avoid that by marking render events that are generated
from the quiescence internals as such, allowing us to ignore them later when evaluating if templates have been rendered.
This does not solve the …

Multiple templates, exec, and wait

---

dependency/vault_common.go
dependency/vault_common_test.go

This PR changes the behavior around refreshing secrets with non-renewable leases to wait for 85-95% of the lease time (rather than 1/6-1/3rd, as with renewable leases). We could also probably increase the range on renewable leases as well to something like 25-35% instead of 16-33%, to eliminate some unnecessarily early refreshing.
Fixes #1126.

Wait longer when refreshing secrets without renewable leases

---

manager/renderer.go

This PR changes the renderer to preserve the destination file permissions when possible (on operating systems that support Go's FileInfo.Sys() interface).
Fixes #1061.

Preserve destination file ownership on unix OSes

---

manager/runner_test.go

This just uses the same approach as in the exec test where it retries with a sleep for the child process to exist.
Builds on the work and closes #1160.
Fixes #1159.

Make exec_once test more reliable

---

README.md

The former wording implied that the plugin would get JSON regardless of
what the arguments to `plugin` were, but the actual implementation just
execs the plugin with the string arguments.
Fixes #1177

Clarify that `plugin` does not JSON encode its args

---

Makefile
docker/light/Dockerfile

This new docker image is suitable for use as a sidecar container in a Kubernetes pod with the `PodShareProcessNamespace` feature. There is more information on why the current images are not a good fit in the linked issue.
Closes #1190

added "light" docker image

---

docker/alpine/Dockerfile

This makes the Docker build process more reliable by providing more than one keyserver.
The same approach is used in https://github.com/hashicorp/consul-k8s/blob/c6b378a7471cebfad947006e6cddc3082bf05081/build-support/docker/Release.dockerfile#L29-L39.

docker: try a variety of gpg key servers

---

Makefile

* use `go env` to get GOPATH and handle multiple paths
* changes to build, dist for easier testing
* remove bashisms
* add pristine build setup for release
* use ./... in tests (removed old vendor workaround)

various Makefile fixes and updates

---

config/config_test.go

Default config tests were supposed to check that environment variables
were read in and added to config. This is how the env variables as put
in as a base default.
Problems were...
a) both compared configs created after setting env vars
b) neither called Finalize() which is what uses the env vars
Basically the tests did nothing. Now they actually test stuff.

fix broken default config tests

---

README.md
cli.go
cli_test.go
config/config.go
config/config_test.go
manager/runner.go
manager/runner_test.go

fix -once to ignore wait/quiescence timers
addresses issues: #1196, #1207, #1209

once-wait-conflict

---

dependency/vault_common.go
dependency/vault_read_test.go

When making unauthenticated secret lookup requests, ignore errors that
result from checking the secret mount type.  If it's a persistent error,
the error on the actual lookup.
This restores behavior prior to #1180 .

Ignore anonymous request failures checking kv status

---

manager/dedup.go

Changed deduplication to achieve the following:
- use one kv key for both lock and data in `consul-template/dedup/<md5>/data`
- automatically cleanup deduplication data in Consul kv store using Consul Sessions
fixes #1158

change dedup to use one key and do auto-cleanup of the dedup kv store

---

docker/light/Dockerfile

I found that when `hashicorp/consul-template:light` tries to talk to my Vault server that is secured with a Let’s Encrypt cert, it fails. (vault fqdn changed to vault.example.com in logs)
```
2019/03/20 18:13:47.270390 [WARN] (view) vault.read(secret/mydatabase): vault.read(secret/data/database): Get https://vault.example.com/v1/sys/internal/ui/mounts/secret/data/database: x509: certificate signed by unknown authority (retry attempt 1 after "250ms")
2019/03/20 18:13:47.398900 [WARN] vault.token: failed to renew: Put https://vault.example.com/v1/auth/token/renew-self: x509: certificate signed by unknown authority
```
If I run `apk add --no-cache ca-certificates` before running consul-template, the problem is fixed.
```
2019/03/20 18:14:22.207209 [INFO] (runner) rendered …
```

add ca-certificates to light docker image

---

.circleci/config.yml
README.md
dependency/client_set_test.go
dependency/dependency_test.go
dependency/vault_agent_token_test.go
dependency/vault_list_test.go
dependency/vault_read_test.go
dependency/vault_write.go
dependency/vault_write_test.go

Replace use of core vault package for testing with an external vault
process. Previously each set of tests that needed vault would create a
vault service in the test process and all tests would use the default
'secret' kv path. Now it uses a separate kv secrets path for each set of
tests, setting the version for each.
The code for starting up the Vault process was based off what was
already used for Consul via its sdk/testutils package.
In the process various test conflicts were addressed and an external
process (consul and vault) process leak was fixed [1].
[1] the leak was caused by use of log.Fatal which calls os.Exit which
exist the process without running any cleanup code.

tests now use an external vault process

---

dependency/catalog_node_test.go
dependency/catalog_service_test.go
dependency/consul_common_test.go
dependency/health_service_test.go

Several calls had version meta-data added in consul 1.5.2 [1]. This
fixes those tests and bumps circleci tests to use consul 1.5.2.
[1] https://github.com/hashicorp/consul/pull/5455

fix test issues due to meta data added to consul

---

README.md
config/template.go
manager/runner.go
template/funcs.go
template/template.go
template/template_test.go

Exposes a knob for consul-template library users to disable some template functions.  Functions like `env` and `plugin` may access sensitive values on host and are best disabled unilaterally.

Knob to blacklist some template functions

---

manager/runner.go

TemplateConfigMapping is used by applications like Nomad that embed
consul-template. By returning a map of pointers, the caller can
compare them against TemplateConfigs passed into the NewRunner method
earlier.
cc @eikenb as we discussed

allow return of TemplateConfigMapping to be comparable

---

dependency/vault_read.go
dependency/vault_read_test.go

When vault.read fails to determine whether a path is KVv2, assume it's
KVv1 and read from the path as passed from user.
Here we fallback to behavior prior to https://github.com/hashicorp/consul-template/pull/1180,
so KVv2 check is for enhancement only.  If user truely lacks access, the
secret lookup call would fail and we report error back.
A customer hit a regression after they upgraded nomad with updated
consul-template, where their templates failed to read approle info
because isKVv2 returned an error.  The case is reproduced in
`TestVaultReadQuery_Fetch_NonSecrets` test.

Read paths unmodified if KVv2 status check fails

---

README.md
template/funcs.go
template/funcs_test.go

During a discussion with @notnoop about https://github.com/hashicorp/nomad/pull/6075, we discovered that _altering_ the path being passed into the `file` function was going to cut off a lot of existing uses of consul-template in Nomad, particularly around the use of the `NOMAD_TASK_DIR` variable.
This PR provides a check but doesn't prefix the path parameter.
cc @schmichael @eikenb

file sandbox: check but don't alter paths passed to 'file'

---

template/funcs.go
template/template_test.go

fix loop to work with different int types

fix loop to work with different int types

---

dependency/vault_read_test.go
dependency/vault_write.go
dependency/vault_write_test.go

Writing to a Vault KV v1 and v2 were both broken.

Issue1252: vault write broken

---

renderer/renderer.go

Instead of opening a new file and manually copying over the contents,
just use a hard link. This has different tradeoffs vs manually copying
(eg. it isn't supported on plan9), but should generally be more robust
and has no race.
This also changes it to just log an error vs returning it, in the case
of a os.Link returning an error, as that causes consul-template to exit
(which we don't want for this).

change backup to use os.Link

---

dependency/vault_common.go
dependency/vault_common_test.go
dependency/vault_read.go
dependency/vault_read_test.go
dependency/vault_token.go
dependency/vault_write.go
dependency/vault_write_test.go

The original problem was that for non-renewable vault secrets that it
was having trouble fetching, it would wait the standard exponential
backoff time plus the configured sleep time (like it does between
successful fetches). When what it should do is use the sleep time
between successful fetches and exponential backoff on failures.
While fixing this I cleaned up the code to make the logic clear.
The issue existed in both vault_read and vault_write, and they shared a
common chunk of renew logic between them and with vault_token. So I
refactored that out into a common function.
Fixes #1224

fix vault retry logic on failed calls

---

renderer/renderer.go
renderer/renderer_test.go

Fix a regression with backup option such that it would only back up once
(os.Link doesn't overwrite). Also added a test to reproduce issue.
Fixes #1270

fix backup to backup more than once

---

dependency/vault_read.go
dependency/vault_read_test.go
dependency/vault_write.go
dependency/vault_write_test.go

An over-zealous refactoring resulted in <-time.After() channel used for
non-renewable sleep to be ignored. I originally had channel of the time
channels but "simplified" it too much. This reworks it the way the sleep
is passed to the next iteration to just pass the time.Duration of the
sleep down the channel, then time.Sleep-ing when reading off the
channel. This way it can see it has a sleep to do, then do it instead of
skipping it as the time hadn't passed yet.
This also let me write a test for it as I don't need to actually sleep
to see that there is something in the channel.
Fixes #1272

fix sleep on non-renewable vault secrets

---

watch/dependencies_test.go
watch/view.go
watch/view_test.go

Rate limit all API calls to Consul to ~1/100ms to keep consul-template
from flooding consul-agent with requests. This takes the idea from #1066
and simplifies it by making it work this way by default instead of
making it a configurable option.
Closes #1066

add basic rate limiting to consul api calls

---

Makefile

it works well  on my env
```
consul-template: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=yBBsvpv1PEzSZNVawlQb/nVRSLofiQGfncQaZ4euB/7hXFeZH6_F2NAJC0gap1/f3JuZNrjcmTkEhzmJfzq, stripped
[root@localhost ~]# ./consul-template -v
consul-template v0.21.0 (0d999b3)
```
Signed-off-by: Liu Hua <sdu.liu@huawei.com>

makefile: add support for arm64 platfrom

---

README.md

Replace `toJson` with `toJSON` in one of the README.md code examples, as the function name is case sensitive and throws errors otherwise.

Fix incorrect code example in README.md

---

.circleci/config.yml
README.md
dependency/catalog_node_test.go
dependency/catalog_services_test.go
dependency/connect_ca.go
dependency/connect_ca_test.go
dependency/connect_leaf.go
dependency/connect_leaf_test.go
dependency/dependency_test.go
dependency/health_service.go
dependency/health_service_test.go
template/funcs.go
template/funcs_test.go
template/template.go
template/template_test.go

Initial Consul Connect support. Target is to allow proxies (nginx, haproxy) to route directly to services inside the mesh network. This is the basic support and reference docs. I'm still working on some examples/intros for each.

Issue 1262 consul connect

---

examples/haproxy-connect-proxy.md
examples/haproxy-connect-proxy/run-haproxy-connect-proxy
examples/nginx-connect-proxy.md
examples/nginx-connect-proxy/run-nginx-connect-proxy

includes helper script to extract config files and run command in screen
session.

add nginx connect example documentation

---

template/funcs.go
template/template_test.go

Currently `sockaddr` function explicitly leaves extra whitespace for every template it renders. This PR removes that whitespace. It also improves the related tests so that the (first) loopback address of the machine is string-matched to "127.0.0.1". Previously the test only checked whether "127.0.0.1" is in the result set, without checking the rendered output for an exact match.
Fixes issue #1314.

Remove extra whitespace from sockaddr func

---

examples/vault-pki.md

Updating the PKI example now that the generate_lease setting on the PKI role is no longer a strict requirement.

Updating examples for PKI relating to the generate_lease requirement.

---

cli.go
cli_test.go
config/config_test.go
config/vault.go
config/vault_test.go
manager/runner.go
watch/view.go
watch/watcher.go

Part of https://github.com/hashicorp/consul-template/issues/1266 . Remove all the code for the deprecated Vault grace field. 
Fixes #1268
Tests:
```
[consul-template][remove-vault-grace](4)$ make test  
==> Testing consul-template
ok      github.com/hashicorp/consul-template    2.042s
ok      github.com/hashicorp/consul-template/child      1.695s
ok      github.com/hashicorp/consul-template/config     0.121s
ok      github.com/hashicorp/consul-template/dependency 6.181s
ok      github.com/hashicorp/consul-template/logging    0.048s
ok      github.com/hashicorp/consul-template/manager    3.334s
ok      github.com/hashicorp/consul-template/renderer   0.102s
ok      github.com/hashicorp/consul-template/signals    0.036s
ok      github.com/hashicorp/consul-template/template   0.120s
? …
```

Remove code/logic for working with Vault grace

---

Makefile

The 32 bit arm build that was supposed to work on both arm5 and arm6
won't run on systems without moving files around due to linking/naming
clashes. So we're changing the arm6 build to use
arm-linux-gnueabihf-gcc, which links against the expected libraries.
At this point we're just going to drop support for arm5 as I don't think
anyone is using it and it's starting to become obsolete.
Fixes #1317

use gnueabihf for 32-bit arm build

---

CHANGELOG.md
README.md
docker/alpine/Dockerfile
docker/alpine/docker-entrypoint.sh

Set USER directrive in the Dockerfile to the consul-template user
created to run consul-template.
Made this change as some organizations security policies require it. The
only reason it wasn't done this way before was to run a chown on the
(possibly) bind mounted directories and this is a bad practice anyways
(who knows who the user matches on the external system).
Only change the alpine image this way as the other 2 (scratch and light)
purposely do as little as possible so they don't even create the user.
Fixes #1321

alpine docker image doesn't run entrypoint as root

---

docker/alpine/Dockerfile

Hey guys,
I appreciate that the container no longer runs as root, but instead runs as the `consul-template` user.
This PR introduces a small change to the Alpine Dockerfile, in that it uses numeric UID/GID values for the `USER` statement. This is required when using PodSecurityPolicies under Kubernetes, to assure the admission controller that the container will not run as root. (Setting a non-numeric value like `USER consul-template:consul-template` is insufficient, since the Dockerfile could simply have renamed the root account, I guess!)
Cheers!
D

Make user non-numeric to satisfy PSP

---

dependency/vault_common.go
dependency/vault_read_test.go

The implicit `/data/` path prefix for kv2 secrets were not properly prepended for secret paths matching `/data*`.
Fixes #1340

dependency: fix kv2 data path prefix checking

---

docker/alpine/Dockerfile
docker/alpine/docker-entrypoint.sh

Alpine comes with tini, which is quite similar to dumb-init. It simplifies a bit the Dockerfile for alpine.
cf. #1245

docker: alpine without docker-base

---

config/vault.go
config/vault_test.go

Adds check in config to change the vault token renew check to not fire
if there is no vault token to renew. Avoids warning spams in the logs.

don't renew vault token when no token is set

---

dependency/vault_read.go
template/template_test.go

The brains/cache is keyed off String() output of a dependency. In this
case the dependency is a versioned vault secret. The problem is that the
vault secret's String() output doesn't contain the version. So the first
version retrieved seeds the cache and all subsequent references use that
version even if they specify a different (or no) version.
Including the version in vault secret String() output fixes this.
Fixes #1350

fix bug looking up versioned vault secrets

---

template/funcs.go
template/funcs_test.go

While looking into an issue I saw these and went ahead and fixed them.
One is taking advantage of map defaults.
The other eliminates struct elements set to their default values.
Almost skipped the PR/review, but decided I should have these sorts of things reviewed as standard practice in case I overlook something.

simplified the code in a couple places

---

dependency/vault_common.go
dependency/vault_common_test.go

There is a subset of non-renewable Vault secrets (static-roles) that have their password rotated on an interval, defined by `rotation_period`.  Their password values change, however, since they're not renewable secrets Consul Template defaults to a 5 minute sleep period.
This updates Consul Template to consider those types of secrets and use their rotation value as the sleep duration for faster updates.

Add lease calculation for rotating secrets

---

dependency/vault_common.go
dependency/vault_common_test.go

#1358 introduced support for templating Vault static roles that have rotating passwords by looking for `rotation_period`.  This does indeed configure Consul Template to have a better sense of how often it should render secrets, but falls short of rendering stale secrets in a timely fashion.
For example, when a static role is created in Vault, the rotation period automatically starts even if the credentials haven't been read.  The time before the next rotation will be very different than the rotation period, so Consul Template will be very out of sync with Vault.
If a secret has a `rotation_period`, Vault will automatically update its `ttl` with the time left before rotation.  Since Consul Template updates the sleep time every time we fetch the secret from Vault, we can simply use the …

Add better sleep configuration for static roles

---

child/child.go

Racing over saving and checking ProcessState. It was checking
ProcessState to see if the command had exited. I tweaked exitCh
to have closing it indicate that the command had exited.
Fixes #1372

fix data race b/w start and kill

---

README.md
manager/runner.go

When using CT as a library, the "standard" way to monitor and know when
to exit is to watch for messages on the TemplateRenderedCh(). The
problem is that the message is sent down that channel before the
commands are run, so the program could exit before the command has run.
The problem is more obvious when CT is run in a transient container,
where even if the commands are run the container might exit before they
finish and they get killed.
Moving the render events to after the command avoids these issues (the
container exit issue also requires a command_timeout > 0s).
Fixes #1369

move render events to after template command

---

README.md
config/config.go
config/config_test.go
config/dedup.go
config/dedup_test.go
manager/runner.go
watch/view.go
watch/watcher.go

This PR aims to introduce a new configuration value, allowing custom block query timeout. I would appreciate feedback on this as I'm not sure if I have covered all the necessary bases.
Closes https://github.com/hashicorp/consul-template/issues/1096

Make timeout for blocking query configurable

---

cli.go
config/config_test.go
config/syslog.go
config/syslog_test.go
logging/logging.go

Currently "consul-template" appear as progname in syslog,
which is quite annoying when you run multiple programs.
Signed-off-by: Jean-Philippe Menil <jpmenil@gmail.com>

Allow to set application name in syslog

---

CHANGELOG.md
README.md
template/funcs.go
template/template.go
template/template_test.go

This can be handy when, for instance, computing the amount of services to spawn depending on some numeral characteristics contained in consul and default values

Add minimum and maximum math functions

---

README.md
template/funcs.go
template/funcs_test.go
template/template.go

this will compute the sha256 hash function and output the hex version
of it.
tests and doc updated.
how to use:
```liquide
{{ "bladibla" | sha256Hex }}
```
this will output 
```
54cf4c66bcabb5c20e25331c01dd600b73369e97a947861bd8d3a0e0b8b3d70b
```

Added sha256Hex function

---

README.md
template/funcs.go
template/template.go
template/template_test.go

Consul-template supports parseJSON. The consul ui supports syntax highlighting for both JSON and YAML so it'd be ncie if consul-template had first-class support for both reading and writing yaml.
This adds a new helper `parseYAML` that works identically to `parseJSON` but accepts YAML.
YAML is much nicer to use for config files than JSON mainly because
comments can be used.
It should be noted that `parseYAML | toYAML` will strip comments with
the current yaml library, but I don't want to go about changing
that huge of a dependency at this stage. `yaml.v3` does support comments,
but it's not super easy to use as you can't just unmarshal to a
`map[string]interface{}` and keep comments.
To work around this, I'd made a plugin `yaml2json` which was just a tiny go program but then I have to …

Add parseYAML helper

---

dependency/catalog_node_test.go
dependency/catalog_nodes_test.go
dependency/catalog_service_test.go
dependency/consul_common_test.go
dependency/health_service_test.go

Some data got added to [Node]TaggedAddresses field. This filters them
out so >1.7 look like <=1.6. I like to be able to test older consul
versions if bugs are filed against them and like the tests to play
along.
Resolves #1359

fix test compatibility issue with consul 1.7

---

README.md
config/consul.go
config/consul_test.go
dependency/client_set.go
manager/runner.go

Add support for Consul namespaces following the same pattern as for
Vault namespaces.
Depends on code in consul's master branch (unreleased). So won't build unless you update the modules dependencies to the correct master commit. Once the upstream code is released, the module dependencies will be updated and added to this PR.

consul namespaces support

---

dependency/vault_common.go
dependency/vault_common_test.go

Vault adds 30 seconds to pad `NotBefore` (configurable) field for certificates issued by the PKI secret engine.  This pad compensates for clockskew.  
An issue I'm seeing with rendering certificates is Consul Template calculates the sleep time using  `cert.NotAfter - cert.NotBefore` of the certificate and configures the read loop for 85-95% of that value, which has the padding included.  In some situations, specifically when TTL is low,  the certificate expires before the application serving it has time to react.
This PR changes Consul Template to instead use the `expiration` value sent along with the certificates.  This means no cert inspection is required and we can do our calculations based on `expiration - time.Now`.  This will give us a better duration to wait.
If the client has …

Allow additional time for PKI certificates to valid

---

renderer/renderer.go
renderer/renderer_test.go

When first rendering a template to a file if the file doesn't exist and
the evaluated template is empty, it wouldn't write the file to disk. It
should always render the file to disk on successful template evaluation.
Fixes: #1393

render initial file even when template is empty

---

dependency/vault_common.go
dependency/vault_common_test.go
dependency/vault_read.go
dependency/vault_read_test.go

Fixes reading Vault KVv2 secrets metadata by not prepending `/data/` path.
<details>
<summary>Test results before change</summary>
```
=== RUN   TestVaultReadQuery_Fetch_KVv2/read_metadata
vault_read_test.go:407: 
Error Trace:	vault_read_test.go:407
Error:      	Received unexpected error:
no secret exists at read_fetch_v2/data/metadata/foo/bar
vault.read(read_fetch_v2/metadata/foo/bar)
github.com/hashicorp/consul-template/dependency.(*VaultReadQuery).Fetch
/Users/kngo/dev/hashicorp/consul-template/dependency/vault_read.go:80
github.com/hashicorp/consul-template/dependency.TestVaultReadQuery_Fetch_KVv2.func2
/Users/kngo/dev/hashicorp/consul-template/dependency/vault_read_test.go:406
testing.tRunner
/usr/local/go/src/testing/testing.go:1039
runtime.goexit …
```

Fix reading Vault KVv2 secrets metadata

---

logging/logging.go

Related to: [Vault 9816](https://github.com/hashicorp/vault/issues/9816) - where dates do not appear in an inconsistent manner.

Writer to log date / time in conistent format like in other places.

---

README.md

Putting this readme change in, the current note wasn't explicit enough for me to realize that the extra `.data` value was syntax and not referencing something key related while reading through the docs.

fix: clarify kvv2 .data value is not a key reference, but a kvv2 syntax change

---

config/config.go
config/config_test.go

Fix issue with block_query_wait setting.
Fixes #1441

Issue 1441 blockquerywait

---

dependency/vault_common.go

Hi folks!
This PR is to fix https://github.com/hashicorp/vault/issues/10715 . The associated Jira for this is: https://hashicorp.atlassian.net/browse/VAULT-1392. 
Thanks so much!

add nil check to secret get [VAULT-1392]

---

logging/logging.go

log.SetOuput() called twice in a row with second, bad setting
overwriting proper one. Looks like it was commit/merge issue.
removing extra SetOutput call fixes it.
Fixes: #1438

fix extra log output

---

CHANGELOG.md
cli.go

version (-v) output should go to stdout

---

docs/templating-language.md
template/funcs.go
template/funcs_test.go
template/template.go

Useful for computing md5sums of strings to be used in places
where sha256 is not supported.

Adds an md5sum function

---

dependency/vault_list.go
dependency/vault_list_test.go
dependency/vault_write.go
dependency/vault_write_test.go
docs/templating-language.md

Changed `secrets` template function behavior for Vault kv-v2 secrets engines. Added behavior similar to [vault cli kv list command](https://github.com/hashicorp/vault/blob/master/command/kv_list.go#L86), which adds `/metadata/` to secret path if secrets engine version is 2. 
Fixes #1275 
Fixes #1274

fixes #1462, 'secrets' template function issue on Vault kv-v2 secrets engines

---

Makefile

Removes workaround with using CGO_ENABLED for ARM builds 
Fixes #1404

Removed special cases for ARM build in Makefile fixes #1404

---

dependency/health_service.go
dependency/health_service_test.go

The IDs need to be different as they are used as the cache keys and
using the same ID means `connect` and `service` would overwrite each
other if both used. (this is bad)
The `connect` function re-uses the health `service` code as it is
identical except for an additional option. When adding connect the ID
was unintentially left the same, it should be different.
Fixes #1458

make connect and health service ids different

---

renderer/renderer.go

When the template config option `perms` is set, the ownership isn't preserved. The problem was the file ownership is preserved in the block that is only run if perms is unset. Ownership should always be preserved.
Note there is no tests as ownership changes are hard/impossible to do cross system. Groups, which you could set, vary to much between systems to make this feasible.
Fixes #1379

fix issue with ownership when perms option is set

---

dependency/vault_common.go
manager/runner.go

It is using a module/global variable at the moment and race tests are
normally run, so it was missed during review. This is the common
sync.Once pattern for this sort of thing that fixes the race.

fix data race issue setting vault's default lease

---

docker/Dockerfile
docker/docker-entrypoint.sh
docker/fetch-n-verify.sh

Update to use new standard of downloading application from official release sources, including cryptographic verification.
Cleans up entrypoint and makes separate init process optional. Standardizing on a minimal Alpine Linux based image.
Note dumb-init was removed as it is not required to for consul-template, as it handles all the signaling properly, and docker has it built in so if a user wants it they can add it by running with `--init`. Shouldn't normally be necessary but might be useful if you have ill-behaved template commands.

new docker image build setup

---

config/config.go
config/config_test.go
docs/observability.md

- Add _LEVEL as suffix to CONSUL_TEMPLATE_LOG
- Remove CT_LOG
- Add reference to the environment variable on the readme file
ref #1328

Simplify log level environment variable usage

---

cli.go
signals/signals_unix.go
signals/signals_windows.go

Go started using SIGURG as a signal used by the runtime to trigger pre-emptive interruptions for parallel execution. This filters them out from being forwarded to the child process (quieting the logging and a bit of overhead).
Fixes #1486

don't send runtime signals to child process

---

child/child.go
child/child_test.go

Need to make sure signals are sent to all processes as sub-shells interfere with signal propagation. Using Setpgid to create a process group for the command and all it's subprocesses fixes this by allowing child to send the signals to the pgid, which thus gets sent to all processes in that group.
This is required for upcoming change to use sub-shells for all executed commands to eliminate need for shell parsing.
With this change it is always set to true and the pgid is always used to send signals to the process(es).
In the future it could be made configurable if needed.
Might be easier to review using the commits. The second commit is test cleanups and fixes where the first one contains the new code and tests.

Add setpgid for all called commands

---

manager/command-prep.go
manager/command-prep_windows.go
manager/runner.go
manager/runner_test.go

Instead of trying to parse the shell command line into arguments for input to exec.Command this replaces that all with passing it to an 'sh -c' call. This will "fix" the wack-o-mole game of spot fixing issues that keep coming up with the shell parsing package.
Windows is handled separately (no 'sh') and is setup to only accept/run a single command.
The code changes are pretty small, bulked out a bit by the need to handle windows separately. Most of the code here are tests I added to try to exercise different cases mentioned in previously submitted issues.
Fixes #1482

replace shell parsing w/ direct shell call

---

docs/templating-language.md
go.mod
go.sum
template/funcs.go
template/template.go
template/template_test.go

Proposed  code for enhancement  in #1499.

add map merge functionality

---

README.md
docs/configuration.md
docs/modes.md
manager/command-prep.go
manager/command-prep_windows.go
manager/runner_test.go

Instead of always using `sh -c` to run command lines on *nix check if it
is a single command (no spaces) and, if so, run that command directly.
This will give users on systems without 'sh' a way to run their commands.
Fixes #1508

no shell call on single command exec on *nix

---

logging/logging.go
logging/logging_test.go
logging/syslog_test.go

Fix issue with syslog writer being skipped by multi-writer.
Fixes #1523

Issue 1523 syslog fix

---

template/funcs.go
template/template_test.go

Vault uses the write API for create+read and the create call doesn't
always take write key/value pairs (requires no fields to be provided)
but these cases would error out on absense of k/v pair. This change
simply skips the k/v check if the parameter string field is empty.
Fixes  #1453

support secret write queries w/ an empty write

---

README.md
cli.go
cli_test.go
config/config.go
config/config_test.go
config/logfile.go
docs/configuration.md
docs/observability.md
logging/logfile.go
logging/logfile_test.go
logging/logging.go

Hi, I spotted this issue and it sounded like an easy one.
Most of the credits go to the Consul folks because while copying the semantics I ended up taking most of the logic too. 
I just added a few tweaks to match consul-template semantics and structure.
This PR adds:
- Consul-like CLI flags used to control the behaviour of the feature
- `log_file` configuration stanza
- updated docs for CLI and config
Fixes #1416

Logging to file

---

template/funcs.go
template/template_test.go

Fix 3 template functions; secrets, caLeafe and node
These functions returned typed pointers as their data field. Template
execution didn't like these typed nil pointer values when looking up
data on them. Changing them to return untyped pointers with an function
signature returning interface{} fixes this as the template knows to have
these always return `<no value>`.
Fixes #1418

fix issue returning typed nil pointers

---

docs/templating-language.md
go.mod
go.sum
template/template.go

This PR adds the [Sprig template functions](https://github.com/Masterminds/sprig) library.  For clarity and ease of documentation, the sprig functions are renamed `sprig_«function»`.

POC: Add sprig library

---

README.md
cli.go
cli_test.go
config/consul.go
config/consul_test.go
dependency/client_set.go
docs/configuration.md
manager/runner.go

Fixes #1429
Tested it out manually and it works.

Add support for providing Consul ACL Token via a file

---

config/config_test.go
config/template.go
manager/runner.go
renderer/file_ownership.go
renderer/file_ownership_windows.go
renderer/renderer.go
renderer/renderer_test.go

Adds support for the `uid` and `gid` entries in the `template` stanza that would ultimately be passed to a `os.Chown` command.
It obviously works only on POSIX and Windows is handled with graceful noop with a warning if the user set `uid` or `gid`
Related issues #639, #1497, #1185 and also nomad/5020
Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

Allow setting user/group ownership of template output

---

README.md
cli.go
config/config.go
config/template.go
config/template_test.go
manager/runner.go
template/template.go

This adds a few `template-error-fatal` options to allow consul-template to continue running in the event of an error while rendering a template.  
The option is exposed individually within each template, globally within the config, and as a global command line flag. The individual template setting overrides the global config setting, and the command line flag overrides all.
No tests yet, but I can create them upon review.
Closes #1419 #1289

add template-error-fatal

---

config/config_test.go
config/template.go
manager/runner.go
renderer/file_ownership.go
renderer/file_ownership_windows.go
renderer/renderer.go
renderer/renderer_test.go

As proposed in https://github.com/hashicorp/consul-template/pull/1531#issuecomment-1023156588, this changes the new file ownership specification from integer `uid`/`gid` to string `user`/`group` that can either be a decimal id or a user/group name. This is both for convenience and for future compatibility with Windows. This change allows us to implement Windows support in the future without changing the public interface in consul-template and Nomad. One catch in the context of Nomad is that user/group names would be looked up on the host, not e.g. inside the Docker container as users may expect.
I also fixed a potential nil dereference via af770eccf6ec1fd2b6722621cea4af50042adb1e and made `Render(...)` fail when trying to set file ownership on Windows analogous to how it fails if `Chmod` …

Allow setting ownership by name

---

cli.go
cli_test.go
config/config.go
config/config_test.go
manager/runner.go
manager/runner_test.go

Allows checking of templates for well formedness without rendering.

add -parse-only option

---

config/config_test.go
config/template.go

This PR simply takes into account `uid` and `gid` settings in the template, introduced in 0.28.0 but replaced by `user` and `group` in 0.29.0, breaking compatibility.
We address the issue by giving precedence to the newer settings but setting the relevant properties upon type conversion if the legacy settings are provided
Uid (0.28.0) -> User (0.29.0)
Gid (0.28.0) -> Group (0.29.0)
Related #1541

Backward compatibility for chown, broken in 0.28.0 -> 0.29.0

---

dependency/dependency_test.go
dependency/vault_common_test.go
dependency/vault_pki.go
dependency/vault_pki_test.go
dependency/vault_read_test.go
docs/templating-language.md
template/funcs.go
template/template.go
template/template_test.go

The new pkiCert template function and its dependency. Common PKI dependency testing setup code was placed in vault_common and called in TestMain. Documentation and template tests round things out.
Most of this is pretty standard new-template-function stuff. The main differing point for this Dependency is that it is specialized to the certificate and uses the rendered template destination file as a cache for the certificate, reading it in and checking the dates to see if it is still valid. If so it reuses it, if not (or if it's not there) it fetches a new one. It tries to handle this 'cache' file as forgivingly as possible, skipping over other CA certificates and text for the PEM encoded/formatted certificate. It should skip any CA, root or intermediary/chain.
Fixes #1259

add new pkiCert template function

---

docs/configuration.md

Add transport section to configuration file documentation.
This is not the best version of docs on transport section so I am open for any advices. But I personally do really want to see transport section documentation at least for dial_timeout, which is really important in some situations.

Add transport section to configuration file

---

template/funcs.go

@eikenb One _very_ tiny change I hope we can sneak in before 0.28.1. I didn't realize that using `user.Current()` relies solely on the `USER` environment variable if the binary isn't built with CGo. We should absolutely just be grabbing the UID and GID from the `os` package.

Remove writeToFile reliance on cgo/$USER for UID/GID detection

---

dependency/connect_ca.go
dependency/connect_leaf.go
dependency/dependency.go
dependency/kv_get.go
watch/view.go

The Block flag returned in the ResponseMetadata from Fetch was
confusing. It sounds like it should be about blocking query, but it is
really about a query that would normally block but instead is returning
no data/nil. The logic in this case is to just loop around to call Fetch
again instead of returning the nil data.
The only case of this is KV Get. Consul returns a 404 for KV lookups
on invalid paths but the GO API ignores this error and returns nil data
(and nil error) instead. By having it just loop again it is basically
letting you to have a blocking-like call on a key that doesn't exist yet
(but could come into existance).
This change fixes the naming of the flag to be more obvious in its
meaning, adding a few reminder comments as well as cleaning up a bit
of use from the confusion.

fix name/use of confusing Block flag

---

docs/configuration.md

I just copied the exec part from the docu and did not even see the typo. consul-template threw the error then =)

fixed typo in docu

---

config/template.go

fixes #1570
The user/group/uid/gid are parsed correctly but lost after calling copy, which leads to renderer doesn't have any info to change file permission when rendering

Fix changing user and group not working

---

dependency/vault_pki.go
manager/runner.go

Fixes #1569
And I found one more bug where the destination is not passed correctly into template, so pkiCert can't find the file and think that is it should issue a new cert instead.

Fix pkiCert not  working correctly

---

manager/runner.go
manager/runner_test.go
template/template.go

The way template configs were being tracked meant that if 2 templates
had the same content but different config otherwise, they would only use
the last config. Having more than 1 template with the same content is
rare but a user ran into it with 2 templates and the same path.
This eliminates the separate tracking of template configs and bundles
them with the templates themselves. Having a 1-1 template/config and
eliminating the separate data structure makes this area of code simpler
to understand and work with while fixing this issue.
This also fixes the TemplateConfigMapping() call which should have kept
backwards compatibility with the signature.

fix bug with 2 templates, same ID, different paths

---

cli.go
signals/signals.go
signals/signals_unix.go
signals/signals_windows.go

User reported missing signals due to a lot of SIGURG signals (Go
scheduler signals). We added code a while back to ignore SIGURG, but
they still are received and take up channel buffer spots. They had to
bump the buffer size to 100 to get it happy.
Reviewing the code there was a handy list of all the signals we accept
in the local signals/ package. So I trimmed out the ignored signals
(SIGURG and SIGCHLD) and passed that to Notify so I wouldn't get the
ignored signals on the channel.
I also bumped the signal channel size to 10 to be a bit more flexible
there as well.
Fixes #1548

reduce os.Signal noise

---

config/nomad.go
dependency/catalog_node.go
dependency/catalog_nodes.go
dependency/catalog_services.go
dependency/health_service.go
dependency/nomad_service.go
dependency/nomad_services.go
template/brain.go

This PR updates implementations of the `sort.Less` interface to use
strictly less-than evalutation of arguments.
https://pkg.go.dev/sort#Interface
// Less reports whether the element with index i
// must sort before the element with index j.
//
// If both Less(i, j) and Less(j, i) are false,
// then the elements at index i and j are considered equal.
// Sort may place equal elements in any order in the final result,
// while Stable preserves the original input or
I suspect `<=` only causes a problem when used in conjunction with sort.Stable
as the results will not actually be stable. However we do in fact use sort.Stable
in consul-template.
```
➜ rg sort\.Stable
dependency/catalog_node.go
126:	sort.Stable(ByService(services))
dependency/catalog_services.go
86: …
```

sort: use strictly less-than for less implementations

---

dependency/dependency.go
dependency/nomad_service.go
dependency/nomad_service_test.go
dependency/nomad_services_test.go
docs/templating-language.md
template/nomad_funcs.go

Nomad's service API is adding a `?choose` parameter (https://github.com/hashicorp/nomad/pull/12862), making use of
[HRW hashing](https://en.wikipedia.org/wiki/Rendezvous_hashing) to deterministically select a subset of services given a hash key (e.g. `allocID`).
Make use of this API in `consul-template` by expanding the `nomadService` function to accept 3 parameters (in addition to the existing 1). These parameters are `<count>`, `<key>`, `<service>`.
Example usage (in Nomad template):
```
{{$allocID := env "NOMAD_ALLOC_ID" -}}
{{range nomadService 3 $allocID "redis"}}
{{.Address}} {{.Port}} | {{.Tags}} @ {{.Datacenter}}
{{- end}}
```
Since Nomad depends on this CT change being included in Nomad before the feature works via Nomad, I'm holding off on the integration test until this PR gets …

nomad: add support for querying consistent subset of services

---

CODEOWNERS

This locks down changes to release directories so that they require approval from release engineering, and so they have service account rights for pipeline runs and backport-assistant functionality.

add codeowners for releng content

---

dependency/vault_common_test.go
dependency/vault_pki.go
dependency/vault_pki_test.go

The code handled the case of getting a cert and using the version on the disk as the cache but missed looping over that logic when the one on disk had expired.
This adds the looping needed to renew the cert when expired and extends the refetch test to validate this functionality.
The second commit could be split out as it's not directly fixing the linked bug, but it is all part of this same code and is needed for this feature to work as intended so I'm including it.
Fixes #1588

Issue 1588: pki cert renew bug + duration/renew logic fixes

---

dependency/vault_pki.go
dependency/vault_pki_test.go
docs/templating-language.md
template/template_test.go

Reworked `PKICert` to return an object with the Cert, the CA and the Private Key. They are stored as stings on a returned struct with appropriate names (Cert, Key, CA).
Fixes #1567 
Note chains were left out as they are difficult/impossible to differentiate from the CA cert and in the file. Plus they are available after the fact from the API.

pkiCert now gets the Cert, Private key and CA

---

child/child.go
child/child_test.go
child/command-prep.go
child/command-prep_test.go
child/command-prep_windows.go
manager/runner.go
manager/runner_test.go

Previously setpgid was set for all commands. This had an unintended
side effect of breaking certain use cases, like using an interactive
'bash' as the command to be executed/managed as a way to debug/test your
setup.
This was also added as part of the conversion from the old (broken)
shell parser to using 'sh -c' subshells for those calls. After that
I added support for single commands and command lists that don't get
wrapped. Using setpgid is not needed on the non-wrapped calls as it was
added to ensure backwards compatibility with signal propagation for
the wrapped commands (the wrapping shell discards some signals).
Note this is an internal change with no documentation changes required.

only use setpgid for 'sh -c' wrapped subshell calls

---

child/child.go
child/child_test.go
cli_test.go
config/config_test.go
config/convert.go
config/convert_test.go
signals/mapstructure.go
signals/nil.go
signals/signals.go
signals/signals_unix.go
signals/signals_windows.go

Converted odd SIGNIL type that wouldn't work with syscall type assertion and allow for differentiating between it and an error into SIGNULL, `syscall.Signal(0)`. SIGNULL works here as it allows for the type assertion to work and for a test to skip the signal when found. It is safe as it already exists in practice in a similar role with the POSIX `kill` command where it indidates no signal.
Fixes #1428
Fixes #1442

Issue 1428 fix no reload signal

---

dependency/vault_pki.go
dependency/vault_pki_test.go
template/template_test.go

This was a classic cut-n-paste error. The PKI code was based on the
existing vault_read.go 'secret' code and missed the fact that the ID of
the pkiCert will be identical for all certs pulled form the same PKI
role path.
The fix will be to adjust the ID to be composed of the pki role path +
the destination path. That should be unique per use case as the
destination path must be unique per Cert.
Fixes #1607

make sure pki IDs are unique

---

README.md
config/nomad.go
config/nomad_test.go
docs/configuration.md
manager/runner.go
watch/watcher.go

This PR introduces a retry configuration option for `NomadConfig`. Since consul-template now includes support for Nomad dependencies, we need this option to maintain behavioral parity with Consul and Vault dependencies.

Add NomadConfig Retry

---

template/template.go
template/template_test.go

Template execute errors would return the values related to the error in certain cases and these could end up in the logs. This makes sure that if those values are vault secrets they are redacted.

filter out vault secrets from template errors

---

Makefile

When in a go workspace, the `go list -m` command emits every module it's been configured with. This addition reduces that list back down to the consul-template module name so that the Makefile works, even when CT is inside a multi-module go workspace.

Updated Makefile to work when Consul-Template is in a Go Workspace

---

docs/configuration.md

This PR adds missing documentation for the setting of template file ownership added in #1541.

Add docs for template file ownership

---

dependency/vault_read.go

**Main problem:** Fetch goroutine in some cases ends with sleep and freezes all allocated objects in its runtime context, even if _cancelChannel_ was triggered.
This bug appears in vault agent and causes memory leak. It can not be fully cured with configuration, but setting specific configuration values can reduce its severity.
**Reproduction of the most severe case:** 
* Set big _DefaultLeaseTtl_ in vault config (default value of 768h is ok, this value need to be big enough)
* Vault agent config field _exit_after_auth_ must be **false**
* Set _TokenTtl_ in agent auth engine to small value (like 10s)
* For template section in agent config: some number of big non-leased secrets need to be used (like kv-v1 without _ttl_ key)
**Observed behavior:** Every time, when agent renews its token we …

fix goroutine leak on fetch sleep

---

cli.go
manager/errors.go
manager/runner.go

Consul-template exits with the code of the child process exit, but it still logs it as an error when it isn't. This changes it to log that at INFO level instead.
Fixes #1282

Log info on child return zero

---

renderer/file_ownership.go
renderer/renderer_test.go

isChownNeeded returned the wrong result if either (exclusive) user or group were set but not the other. It uses a guard value but only compares both at the start and doesn't take this into account on the final comparison which compares both against the current values.
IE. it always returns true in these cases as the guard value is never going to be the same as an real file value.
Fixes #1651

isChownNeeded bad when only user/group (!both) set

---

Makefile

When updating the Makefile for Go Workspaces, I accidentally single quoted where I needed double quotes causing the version hash to not print in the version output properly.

Fix incorrect quoting in Makefile

---

config/nomad_test.go
dependency/client_set.go
dependency/dependency.go
dependency/dependency_test.go
dependency/nomad_var_get.go
dependency/nomad_var_get_test.go
dependency/nomad_var_list.go
dependency/nomad_var_list_test.go
dependency/nomad_var_structs.go
docs/templating-language.md
go.mod
go.sum
manager/dedup_test.go
manager/runner.go
renderer/renderer_test.go
template/nomad_funcs.go
template/template.go
template/template_test.go
watch/vault_token_test.go

This PR extends consul-template to support NomadVariables. It adds 4 additional functions:
- nomadVars
- nomadVarsSafe
- nomadVar
- nomadVarExists
There is a circular dependency issue with Nomad, so the tests won't pass until Nomad has released a version that contains secure variables. I'm not sure how exactly to manage this, but I need to get the PR up at least.

Support Nomad Variables

---

Dockerfile

my organization is currently auditing whether any docker images we run are currently using the root user. From dockerhub it looks like this line expands out to `USER :` since the env var names don't match. (see https://hub.docker.com/layers/hashicorp/consul-template/0.29/images/sha256-32f8ffb8db51809d93488527d63f97d267e2a10c0cbe96dfa5cbc408266211ab?context=explore) This would fix this so that your images are run as the user you create earlier in the dockerfile.

fix: user set in dockerfile

---

child/child.go

Force killing was using the builtin Process.Kill() command that signals the process with os.Kill but doesn't take into account if Setpgid has been set so doesn't kill any subprocesses (if the command was run as a shell string that uses Setpgid to be sure signals propogate to any spawned sub-processes).
This changes it to use the internal signal method which checks Setpgid and uses the process group id to kill all processes in the group.
--
Note that I wasn't able to come up with a good test that runs a subshell in a subshell. If anyone has a good idea for testing this please let me know.
Fixes #1666

use internal signal implementation for force kill

---

child/child_test.go
cli.go
cli_test.go
config/config.go
config/config_test.go
dependency/dependency_test.go
dependency/file.go
dependency/file_test.go
dependency/vault_agent_token_test.go
logging/logfile_test.go
logging/logging.go
logging/syslog_test.go
main_test.go
manager/manager_test.go
manager/runner_test.go
renderer/renderer.go
renderer/renderer_test.go
template/funcs.go
template/template.go
template/template_test.go
test/helpers.go
watch/watch_test.go

The `ioutil` package has been deprecated since Go 1.16 and this project uses 1.19. This PR updates the code to use equivalent functions from the `io` and `os` packages.
Fixes #1675

Update deprecated ioutil calls

---

template/funcs.go
template/template_test.go

- Use `golang.org/x/text/cases` package in the `toTitle` function. Previous method `strings.Title` has been deprecated since Go 1.18. 
- Add a test to title case a sentence with unicode punctuation and a rocket emoji 🚀 
Fixes #1677

Fix 'toTitle' function for a better support for word boundaries and unicode punctuation

---

template/funcs.go
template/template_test.go

While working on #1676 and #1677 I struggled with minor formatting issues in the `template` package. This PR fixes those issues by formatting the code according to `go fmt`.
Other packages are ok.

Fix code formatting for template package

---

config/convert_test.go
manager/runner_test.go
template/funcs.go

In detail:
- `config/convert_test.go`: `time.Second` & others are already represented (internally) by an `int64` so type conversion after multiplication is not needed
- `manager/runner_test.go`: Same as above + `act` is defined as a string from the start, no need for conversion
- `template/funcs.go`: Upon reflection `v.Int()` already returns an `int64`

Remove unnecessary type conversions from various places

---

dependency/vault_read_test.go

A Vault related test in `dependency/vault_read_test.go` creates an `operator` policy for creating restricted tokens later on. The call is missing an `err` check and this PR fixes that.

Add missing err check to Vault read test

---

config/transport.go

See this ticket for some details...
https://github.com/hashicorp/consul-terraform-sync/pull/164
Summary: http.MaxIdleConnsPerHost was default to a very low value that caused TCP connections to not be reused across dependency monitoring. Only ~1 connections were being reused from the initial set of hcat requests to Consul, and the remaining dependencies required establishing a new connection.
Fixes #1603

config default tweaks based on cts research

---

child/child.go

In cases it would just send the signal instead of matching against configured signals for special behavior.
Fixes #1671

respect reload/kill configured signals

---

config/config.go
docs/configuration.md
manager/runner.go
watch/dependencies_test.go
watch/view.go
watch/view_test.go
watch/watcher.go

Works at the view/polling level, so should cover all data types. It fails on 2nd attempt as first attempt is special cased.
Fixes #1637

option to exit with error on failed data lookup

---

cli.go
config/config_test.go
config/vault.go
dependency/client_set.go
dependency/client_set_test.go
docs/configuration.md
manager/runner.go

This adds a new configuration item for Vault, `ClientUserAgent`. When set, Consul Template will use the set `User-Agent` when making requests to Vault.
This change is being made as part of a broader effort for Vault Agent to send its version as part of a `User-Agent` string in requests to Vault. Agent will then consume the latest version of `consul-template`, then use this new config to set the correct `User-Agent`.
Tests were of course added to validate that this works as expected, but let me know if there's anything else I should be testing as part of this change.

VAULT-12940 Add ability to configure Vault client user agent

---

CHANGELOG.md
manager/runner.go

Switching to more inclusive language by replacing "sane" with "reasonable".

Replace uses of the word "sane"

---

docs/templating-language.md

Adding an example to the pkiCert docs showing how to use writeToFile to write the Key and Certs separately.
Related to https://github.com/hashicorp/vault/issues/19787

docs/pkiCert: adding a writeToFile example

---

config/convert_test.go
config/vault.go
dependency/catalog_datacenters_test.go
dependency/dependency.go
dependency/kv_get_test.go
dependency/kv_keys_test.go
dependency/kv_list_test.go
dependency/nomad_service_test.go
dependency/nomad_var_get_test.go
dependency/nomad_var_list_test.go
dependency/vault_list_test.go
dependency/vault_read_test.go
dependency/vault_write.go
dependency/vault_write_test.go
manager/runner.go

Minor fixes, including:
- Use a more descriptive `FileMode` in tests and in octal format to match `os.Filemode`
- Fix tag in `ClientUserAgent` field for `VaultConfig`
- Omit comparison to bool constants
- Remove unconditionally terminated loops from various tests
- Remove unused `printWarnings()` method from `VaultWriteQuery`
- Remove `once` parameter from `newWatcher()` as it's reachable through `config` parameter as well
Figured it would make sense to put it all into a single PR rather than multiple (almost) one-line changes :)

Various code quality fixes/linting

---

docs/templating-language.md
template/funcs.go
template/funcs_test.go
template/template.go
template/template_test.go

Useful for cases where data in Consul has to be rendered into HMAC SHA256 hashes, where the shared key is stored in Vault. Example snippet:
```
{{ range ls "foo" }}
{{ $msg := .Value -}}
{{ with secret "secret/foo" }}{{ .Data.data.bar | hmacSHA256Hex $msg }}{{ end -}}
{{ end }}
```
Fixes #1701.

Add function for HMAC SHA256

---

cli.go
cli_test.go

Add the following CLI parameters and tests for each one:
- `exec-env-pristine`
- `exec-env-custom`
- `exec-env-allowlist`
- `exec-env-denylist`
As `custom`, `denylist` and `allowlist` are presented in slices, it is possible to define the same parameter multiple times. This behaviour matches how other HashiCorp tools handle similar cases, such as:
- `consul agent` and `--node-meta<key:value>` parameter
-  `vault kv get` and `-header=<key=value>`
Fixes #1051

CLI support for exec env configs

---

.github/workflows/build.yml

Replace `set-output` commands in GH Actions workflows by setting outputs to temporary environment variables read by the Actions runners.
More information available in [this Github blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and [environment files documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).
Fixes #1748.

Deprecate set-output commands in GH Actions 'build' workflow

---

dependency/catalog_datacenters.go

Reverts hashicorp/consul-template#1746
reverting this as there could be some performance implication

Revert "fix: datacenter sort should be by RTT and is instead lexical"

---

CHANGELOG.md
dependency/catalog_node_test.go
dependency/catalog_nodes_test.go
dependency/catalog_service_test.go
dependency/health_service_test.go
version/version.go

- Prepping repo for next release
- Fixing broken specs 
- Changelog updates

[NET-5176] Fix repo tests, changelog and bump repo version to 0.33.0

---

child/child.go

Go version was updated to 1.20 in #1783 and with that `math/rand` no longer requires an explicit seed for the random number generator. See https://github.com/golang/go/issues/54880 for more information. This PR removes that call.
Related to lint settings being worked on at #1774.

chore: remove explicit math/rand seed

---

dependency/vault_common.go
dependency/vault_pki.go
dependency/vault_read.go
dependency/vault_write_test.go

Minor refactor for Vault related functionality in the `dependency` package:
- Use Vault `NewLifetimeWatcher()` instead of `NewWatcher()` as it is deprecated ([see API client reference here](https://github.com/hashicorp/vault/blob/api/v1.9.2/api/lifetime_watcher.go#L185C6-L187)). For compatibility purposes, `RenewBehaviour` is the same as with the previous functionality.
- Use Vault `ReadRaw()` instead of `RawRequest()` as it is deprecated ([see API client reference here](https://github.com/hashicorp/vault/blob/api/v1.9.2/api/client.go#L1279-L1288)).
- For `VaultReadQuery` dependency, remove `opts` from being passed further down to other functions as it is and won't be used. Query parameters (like `version`) for Vault read calls are stored in a separate `queryValues` field. Other …

chore: refactor deprecated Vault calls

---

go.mod
go.sum

Fixes for CVEs in relation to crypto: https://cve.report/CVE-2023-29409

Bump crypto package and go version

---

README.md

`make build` was removed a couple of version back from the makefile so this instructions are incorrect

Remove outdated instructions

---

.github/workflows/ci.yml

- allow us to run consul with enterprise binary for testing enterprise feature

Setup for consul ent testing

---

dependency/catalog_node.go
dependency/catalog_node_test.go
dependency/catalog_nodes.go
dependency/catalog_nodes_test.go
dependency/catalog_service.go
dependency/catalog_service_test.go
dependency/catalog_services.go
dependency/catalog_services_test.go
dependency/dependency.go
dependency/health_service.go
dependency/kv_get.go
dependency/kv_get_test.go
dependency/kv_keys.go
dependency/kv_keys_test.go
dependency/kv_list.go
dependency/kv_list_test.go
docs/templating-language.md

Note: ensure you have consul running 
- insert into kv in default namespace and partition 
```
consul kv put "hashi/test" "default"
```
- create a file `in.tpl`  insert the following to retrieve that key 
```
{{ key "hashi/test" }}
```
- ensure it can still read the key
```
consul-template -template "in.tpl:out.txt" -once
```
- verify: your `out.tpl` file should have:
```
default
```
- create a new consul namespace/partition (sorry these names aren't too creative :D) 
```
consul partition create -name "partition"
consul namespace create -name "partition-ns" -partition "partition"
```
- store kv in the new partition/namespace created above
```
consul kv put -partition "partition" -namespace "partition-ns" "hashi/test" "part
ition"
```
- update your `in.tpl` to include namespace and …

[NET-1484] Support for namespaces, partitions in consul endpoints

---

CHANGELOG.md
dependency/consul_peering.go
dependency/consul_peering_test.go
dependency/dependency.go
dependency/dependency_test.go
docs/templating-language.md
template/funcs.go
template/template.go
template/template_test.go

- new template function to access consul peerings in consul template.
- test cases for the same.
- Changelog
Through unit tests.
[HashiCorp engineers only. Community PRs should not add a changelog entry.]::
[Changelog entries should use present tense, e.g. "Add support for..."]::

[NET-6966] consul-template support for listing peerings

---

CHANGELOG.md
dependency/catalog_services.go
dependency/catalog_services_test.go

- bug fix for SeatGeek: Services function in CT (consul-template) does not update the namespace for each services API call
- opts should be defaulted to the opts at query creation.
- then they should be merged with the opts present in Fetch.
- currently the merge was the other way around.
- ENT test support is not there, so no test cases added as of now.

[NET-7571]SeatGeek

---

dependency/health_service.go
dependency/health_service_test.go

This would cause Consul to return the same data for service queries regardless of the peer query param.

Fix bug with peer not being part of the key

---

cli_test.go
config/config.go
config/config_test.go
manager/runner.go
renderer/renderer.go
template/template.go
template/template_test.go

Some consumers of `consul-template` use it like a library, where the application runs the runner in-process. For projects like Nomad which need to run with a high level of privilege, this is problematic in that its challenging to secure the operations that read and write from disk without running the entirety of CT as an external process (which carries a lot of overhead for Nomad workloads).
Add a `RendererFunc` and `ReaderFunc` interface to allow Nomad to inject a sandboxed subprocess when reading from disk and writing to disk.
This implementation is currently being used in Nomad 1.7.4, 1.6.7, and 1.5.14 as a mitigation for https://github.com/hashicorp/nomad/issues/19888. See https://github.com/hashicorp/nomad/commit/df865033494574de14da687c999d66b799899b21 for example usage.
Required …

render templates with external functions

---

manager/runner.go
watch/view.go
watch/view_test.go
watch/watcher.go

Creates a channel, ServerErrCh that will surface server errors back to the caller. This channel will hold a maximum of one error at a time. 
The purpose of this, is to allow Vault Agent and Vault Proxy to re-authenticate if the error message from the server indicates that the token is an "invalid token". More information on this initiative here: https://hermes.hashicorp.services/document/1yTtWJEvyoYLPkYRQ3lxs6dHmqAVyC177BMEBEXuu8fE?draft=false

Create ServerErrCh to surface server errors back to caller.

---

manager/runner_test.go
watch/watcher.go
watch/watcher_test.go

A Nomad user reported an issue where `View.poll` goroutines were being leaked when using large templates. When the runner's `Run` method is in-flight and the runner concurrently receives `Stop`, it's possible for the watcher to stop dependencies via stop and then immediately recreate them. Because the `Stop` method has returned, the caller will assume that all goroutines have been stopped, and this causes the `View.poll` goroutines to be leaked. The race condition for this case is very narrow, but is most likely to occur when the user has both a very large number of dependencies, short secret leases, and the `Wait` configuration is nil.
Add a `stopped` flag to the `Watcher` which is set on `Stop`, and check whether this field has been set before adding a new dependency.
Ref: …

prevent dependencies from being added after stop

---

.golangci.yml
child/command-prep.go
config/nomad_test.go
manager/runner.go

Example errors: https://github.com/hashicorp/consul-template/actions/runs/8367173344/job/22908983809?pr=1899

Fix lint errors/deprecated golangci opts

---

dependency/vault_pki.go
dependency/vault_pki_test.go

closes #1612
The current logic for determining how long a certificate rotates depends on the duration (`time the certificate expires` - `the current time`) which seems to have weird corner cases that cause the certificate to be renewed at much later than 86-93% of the ttl which was originally intended. This updates the code to determine a `rotationTime` (i.e. the time that is NotBefore + 86-93% of the lifespan of the certificate) and sleeps until the `rotationTime` occurs.
Once this is merged, I can follow with a fix for https://github.com/hashicorp/consul-template/issues/1646

use lifespan instead of duration for calculating when cert should be rotate

---

dependency/vault_pki.go
dependency/vault_pki_test.go

closes https://github.com/hashicorp/consul-template/issues/1646

allow vault_pki renewal interval to be configured by VaultLeaseRenewalThreshold

---

CHANGELOG.md
version/version.go

We need to update the consul-template version so that it can be used to fix a Vault Issue : https://hashicorp.atlassian.net/browse/VAULT-16121 that does not regenerate pki certificates at the correct cadence.

Pre Release Updates for 0.37.5

---

README.md

What is in this PR?
- We have added the compatibility matrix in the README.md which gives everyone a view about how different versions of CT work with different versions of Consul.
Why this PR?
- https://hashicorp.atlassian.net/browse/NET-8062. Support team requested this from us.
How did we test?
- We built docker images with Consul and CT binaries inside them, started Consul and then ran all the CT tests to see whether they pass.
- If they failed we analysed them and checked whether the failure was due to a hardcoded value in the test, removed them and re-ran.
- The code is checked in here https://github.com/hashicorp/consul-template/pull/1907

[NET-8062] Consul-CT compatibility matrix

---

dependency/consul_peering_test.go

changed the `TestListPeeringsQuery_Fetch` test so that it also:
- creates a blocking query
- creates a new peer
- asserts that the blocking query detects the new peer.

[NET-9084] - change peering fetch test to assert blocking query behavior.

---

go.sum
template/funcs.go
template/funcs_test.go
template/template.go

This PR adds a `byPort` function to consul-template.
Similar in nature to the existing `byTag` function, `byPort` will group services in a list by port number.
<details>
<summary>Example</summary>
Input
```yaml
[
{ID: "serviceA", Port: 8080},
{ID: "serviceB", Port: 8080},
{ID: "serviceC", Port: 9090}
]
```
should return
```yaml
{
8080: [
{ID: "serviceA", Port: 8080},
{ID: "serviceB", Port: 8080},
],
9090: [
{ID: "serviceC", Port: 9090}
]
}
```
</details>
`HealthService`, `CatalogService` and `NomadService` types are supported. Notably, `CatalogSnippet` ([code](https://github.com/hashicorp/consul-template/blob/f48de7fa7489c5662cb56afd4f08c87a6438d680/dependency/catalog_services.go#L29-L33)) and `NomadServicesSnippet` ([code](https://github.com/hashicorp/consul-template/blob/29885821b9d62f06 …

[NET-9450] Add byPort function for grouping services by port number

---

CHANGELOG.md
version/version.go

This release adds functionality in a backwards-compatible manner:
- `byPort` function for grouping Consul services by port
- `partitions` function for listing Consul partitions in the local datacenter
- `exportedServices` function for listing services exported from a given partition

[NET-9610] Prep for release of v0.38.0

---

dependency/consul_exported_services.go
dependency/consul_exported_services_test.go

The `/v1/config/exported-services` endpoint ([docs](https://developer.hashicorp.com/consul/api-docs/config#list-configurations)) -- which is currently used for the `exportedServices` func -- simply returns the config entries as they exist. This means that a wildcarded export, for example, will simply return the wildcard.
In contrast, the `/v1/exported-services` endpoint ([docs](https://developer.hashicorp.com/consul/api-docs/exported-services)) -- introduced in https://github.com/hashicorp/consul/pull/20015 -- resolves wildcards to the resulting list of exported service names and resolves sameness groups to the resulting list of peers and partitions.
With this change, wildcard exports are now expanded out to the full list of exported services instead of just `*` for the service name: …

Use /v1/exported-services instead of config entry list for exportedServices func

---

CHANGELOG.md
version/version.go

This release includes one bug fix and one improvement for the `exportedServices` function (see `CHANGELOG.md`)

[NET-9900] Prep for release of v0.38.1

---

.golangci.yml
cli.go
go.mod
go.sum
manager/runner.go

- Integrated systemd notification support using github.com/coreos/go-systemd/v22/daemon.
- Updated manager/runner.go to signal readiness to systemd.
- Modified .golangci.yml to include github.com/coreos/go-systemd in linters-settings.
- Updated dependencies in go.mod and go.sum for github.com/coreos/go-systemd/v22 v22.5.0.
**Purpose**:
- This enhancement enables the application to efficiently notify systemd about its readiness, improving overall service management capabilities and alignment with modern system practices.
See the description of PR #1794 and #1841 respectively for detail info.

feat: Add support for systemd notify

---

dependency/vault_pki.go
dependency/vault_pki_test.go

This is for Github issue https://github.com/hashicorp/consul-template/issues/1961
This provides the `CAChain` data on the `with pkiCert` function. This is necessary to support rotation of a intermediary CA without causing service interruptions.
Instead of using this template:
```
{{- with pkiCert "pki/astundzia/issuing_ca/issue/genctl-consoleproxy-tls" "common_name=console-proxy.vpc.cloud.ibm.local" "format=pem" -}}
{{ .Cert }}
{{ .Key  }}
{{ .Key | writeToFile "/etc/certs/client.key" "" "" "0644" }}
{{ .Cert | writeToFile "/etc/certs/client.crt" "" "" "0644" }}
{{- end }}
{{- with secret "pki/astundzia/issuing_ca/cert/ca_chain" -}}
{{- .Data.ca_chain }}
{{- .Data.ca_chain | writeToFile "/etc/certs/client.crt" "" "" "0644" "append,newline" }}
{{ end }}
```
I can instead just use:
```
{{- …
```

Enhance with pkiCert template to return full CA chain

---

manager/runner.go
manager/runner_test.go

When quiescence is configured and there are multiple templates, they will trigger eachothers quiescence timers indefinitely. This can be avoided by not ticking the timer of other templates when an individual template's timer fires.
Fixes: [GH #1427](https://github.com/hashicorp/consul-template/issues/1427), [GH #20618](https://github.com/hashicorp/nomad/issues/20618)

fix: add quiescenceRun flag to avoid render loops

---

dependency/vault_read.go
dependency/vault_read_test.go

Add support for the [Vault KV subkeys](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#read-secret-subkeys) API path.
Cf. https://github.com/hashicorp/consul-template/issues/2015

support Vault KV subkeys to avoid consul-template adding /data/ to the path

---

.github/workflows/lint.yml

- pin golangci-lint version to v1.62.0 instead of using latest version in the lint workflow since lint action is failing with latest version.

fix: pin golangci-lint version to v1.62.0 in workflow

---

dependency/consul_peering.go
dependency/dependency.go

The previously used `DefaultContextTimeout` does not work well with the user-definable `WaitTime`, which can easily exceed this global timeout.
Fixes #2041

fix: timeout issues for list.peerings
